// AUTO-GENERATED by gen:image-dims. Do not edit by hand.
// Intrinsic dimensions of manual images (fetched from GitHub at runtime) so the
// Img component can reserve space and avoid layout shift.
export const MANUAL_IMG_DIMS: Record<string, { w: number; h: number }> = {
	"bottom-bar.png": { w: 1160, h: 224 },
	"distribution.png": { w: 2560, h: 1365 },
	"editor-layout.png": { w: 2560, h: 1368 },
	"generator.png": { w: 2560, h: 1371 },
	"location-editor.png": { w: 2559, h: 1360 },
	"map-list.png": { w: 2560, h: 1366 },
	"pano-controls.png": { w: 1369, h: 769 },
	"plugin-marketplace.png": { w: 892, h: 548 },
	"review-sessions.png": { w: 804, h: 311 },
	"score-bounds.png": { w: 1128, h: 659 },
	"selection-algebra.png": { w: 2548, h: 1360 },
	"selections.png": { w: 2559, h: 1356 },
	"settings.png": { w: 858, h: 950 },
};
