// Generated by dts-bundle-generator v9.5.1

/// <reference types="google.maps" />

import { ComponentType } from 'react';

export interface PluginSettingDef {
	key: string;
	label: string;
	type: "boolean" | "string" | "number";
	default: unknown;
}
interface Plugin$1 {
	id: string;
	name: string;
	description?: string;
	icon: string;
	comingSoon?: boolean;
	core?: boolean;
	settings?: PluginSettingDef[];
	activate(): void | (() => void);
	modal?: ComponentType<{
		onClose: () => void;
	}>;
	sidebar?: ComponentType<{
		onClose: () => void;
	}>;
	locationPanel?: ComponentType;
}
export type PluginBehavior = Partial<Plugin$1> & {
	activate(): void | (() => void);
};
declare function registerPlugin(plugin: Plugin$1 | PluginBehavior): void;
/**
 *  A swap-removal from a render cell. JS must move the last element into `cell_index`
 *  and pop the array to mirror the Rust-side swap-remove.
 */
export type CellRemoval = {
	cell: string;
	cellIndex: number;
	id: number;
};
/**
 *  Override the RGBA color of a single marker within a cell (used when selection
 *  membership changes without a position change).
 */
export type ColorPatchEntry = {
	cell: string;
	cellIndex: number;
	r: number;
	g: number;
	b: number;
	a: number;
};
/**
 *  A commit's delta, returned to the frontend for the per-commit diff viewer.
 *  An updated location appears in both `created` (new) and `removed` (old).
 */
export type CommitDelta_Serialize = {
	created: Location_Serialize[];
	removed: Location_Serialize[];
};
/**  Metadata for a single commit, returned to the frontend for the commit history UI. */
export type CommitInfo = {
	id: string;
	mapId: string;
	parentId: string | null;
	message: string | null;
	treeHash: string | null;
	added: number;
	removed: number;
	modified: number;
	locationCount: number;
	createdAt: string;
};
/**
 *  How a field's values are compared when measuring how strongly it separates
 *  groups (selection disambiguation). The only un-inferrable property a field can
 *  declare is circularity (heading/azimuth=360, hour-of-day=24, month=12);
 *  everything else is inferred from `ExtraFieldType`.
 */
export type ComparisonType = {
	type: "linear";
} | {
	type: "circular";
	period: number;
} | {
	type: "categorical";
};
/**  Aggregate database statistics for the debug panel. */
export type DbStats = {
	maps: number;
	locations: number;
	tags: number;
	commits: number;
	dbSizeBytes: number;
	journalMode: string;
	foreignKeys: boolean;
};
/**  Row count for a single SQLite table, used in the debug diagnostics panel. */
export type DbTableInfo = {
	name: string;
	rows: number;
};
/**
 *  Preview data for importing a file into the currently open map.
 *  Unlike bulk import, this shows per-field counts so the user can
 *  selectively drop fields (heading, panoId, etc.) before importing.
 */
export type EditorImportPreview = {
	locationCount: number;
	tags: Tag[];
	fields: FieldCount[];
	warnings: string[];
	/**  Temp-file path to preview positions: interleaved LE f32 `[lng, lat]` pairs. */
	previewPositionsPath: string;
	/**  `[west, south, east, north]` bounding box of the import, for map auto-focus. */
	bounds: [
		number,
		number,
		number,
		number
	] | null;
};
/**
 *  Combined result of an editor import: the mutation delta (for render pipeline)
 *  plus import-specific metadata.
 */
export type EditorImportResult_Serialize = {
	importedCount: number;
	warnings: string[];
} & MutationResult_Serialize;
/**
 *  Configuration for JSON export. Controls which fields are included and
 *  whether the export covers all locations or a specific selection.
 */
export type ExportOpts = {
	exportZoom: boolean;
	exportUnpanned: boolean;
	exportExtras: boolean;
	/**  When `Some`, restricts export to these location IDs (e.g. current selection). */
	scope: number[] | null;
	mapName: string;
	/**
	 *  Serialized `{id: {name, color}}` tag definitions from the store, used to
	 *  convert numeric tag IDs back to human-readable names in the output.
	 */
	tagsJson: string;
	extraFieldsJson: string | null;
};
/**
 *  Schema definition for a single `Location.extra` field. Stored in the map's
 *  `extra.fields` JSON. For enum types, `values` lists valid options and `labels`
 *  provides display names.
 */
export type ExtraFieldDef = {
	type: ExtraFieldType;
	label?: string | null;
	values?: string[] | null;
	labels?: {
		[key in string]: string;
	} | null;
	/**
	 *  Optional override for how this field is compared during disambiguation.
	 *  `None` => inferred from `field_type` on the analysis side.
	 */
	comparison?: ComparisonType | null;
};
/**
 *  Type discriminant for `Location.extra` field definitions.
 *  Determines how the field is displayed and filtered in the UI.
 */
export type ExtraFieldType = "string" | "number" | "date" | "month" | "enum";
/**
 *  Field presence count for the editor import preview dialog, letting
 *  the user see which optional fields exist and decide which to keep/drop.
 */
export type FieldCount = {
	key: string;
	count: number;
};
/**
 *  Summary of a single map found during bulk import preview.
 *  Shown in the import dialog so the user can select which maps to import.
 */
export type ImportPreviewEntry = {
	name: string;
	folder: string | null;
	locationCount: number;
	tagCount: number;
	warnings: string[];
};
/**  Result returned per map after a successful bulk import. */
export type ImportedMapInfo = {
	id: string;
	name: string;
	locationCount: number;
	tagCount: number;
};
/**
 *  Partial location update from JS. `None` fields are unchanged; `Some(None)` on
 *  nullable fields (panoId, extra, modifiedAt) explicitly sets the field to null.
 */
export type LocationPatch_Deserialize = {
	lat?: number | null;
	lng?: number | null;
	heading?: number | null;
	pitch?: number | null;
	zoom?: number | null;
	panoId?: string | null;
	flags?: number | null;
	tags?: number[] | null;
	extra?: any | null;
	createdAt?: string | null;
	modifiedAt?: string | null;
};
/**
 *  A single Street View location on a map.
 *
 *  This is the atomic unit of data in the system. Locations are stored columnar
 *  in Arrow IPC on disk and addressed by `id` everywhere. The `id` is unique
 *  within a map and assigned by the store's monotonic allocator.
 */
export type Location_Deserialize = {
	/**
	 *  Monotonically increasing within a map. Zero is a sentinel meaning
	 *  "not yet assigned" (used during import before IDs are allocated).
	 */
	id?: number;
	lat: number;
	lng: number;
	heading: number;
	pitch: number;
	/**  Street View zoom level (0-5), not map zoom. */
	zoom: number;
	panoId: string | null;
	/**  See [`LocationFlags`]. */
	flags: number;
	/**  Tag IDs applied to this location. References `Tag.id`. */
	tags: number[];
	/**  Arbitrary key-value metadata */
	extra?: any | null;
	/**  ISO 8601 timestamp, generated via `util::now_iso()`. */
	createdAt: string;
	modifiedAt?: string | null;
};
/**
 *  A single Street View location on a map.
 *
 *  This is the atomic unit of data in the system. Locations are stored columnar
 *  in Arrow IPC on disk and addressed by `id` everywhere. The `id` is unique
 *  within a map and assigned by the store's monotonic allocator.
 */
export type Location_Serialize = {
	/**
	 *  Monotonically increasing within a map. Zero is a sentinel meaning
	 *  "not yet assigned" (used during import before IDs are allocated).
	 */
	id: number;
	lat: number;
	lng: number;
	heading: number;
	pitch: number;
	/**  Street View zoom level (0-5), not map zoom. */
	zoom: number;
	panoId: string | null;
	/**  See [`LocationFlags`]. */
	flags: number;
	/**  Tag IDs applied to this location. References `Tag.id`. */
	tags: number[];
	/**  Arbitrary key-value metadata */
	extra?: any | null;
	/**  ISO 8601 timestamp, generated via `util::now_iso()`. */
	createdAt: string;
	modifiedAt?: string | null;
};
export type MapData = {
	meta: MapMeta;
};
/**
 *  Top-level `extra` JSON blob on a map row. Currently only holds field definitions,
 *  but structured as an object to allow future extensions.
 */
export type MapExtra = {
	fields?: {
		[key in string]: ExtraFieldDef;
	} | null;
};
/**
 *  Full metadata for a map, deserialized from the SQLite `maps` row.
 *  JSON columns (settings, tags, extra, etc.) are parsed into typed structs.
 */
export type MapMeta = {
	id: string;
	name: string;
	description: string;
	folder: string | null;
	settings: MapSettings;
	scoreBounds: ScoreBounds;
	extra: MapExtra;
	tags: {
		[key in string]: Tag;
	};
	labels: string[];
	locationCount: number;
	createdAt: string;
	updatedAt: string;
	lastOpenedAt: string | null;
};
/**
 *  Partial update for map metadata. Only non-`None` fields are written.
 *  `folder: Some(None)` explicitly unsets the folder (moves to root).
 */
export type MapMetaPatch = MapMetaPatch_Serialize | MapMetaPatch_Deserialize;
/**
 *  Partial update for map metadata. Only non-`None` fields are written.
 *  `folder: Some(None)` explicitly unsets the folder (moves to root).
 */
export type MapMetaPatch_Deserialize = {
	name?: string | null;
	description?: string | null;
	folder?: string | null;
	settings?: MapSettings | null;
	scoreBounds?: ScoreBounds | null;
	extra?: MapExtra | null;
	tags?: {
		[key in string]: Tag;
	} | null;
	labels?: string[] | null;
};
/**
 *  Partial update for map metadata. Only non-`None` fields are written.
 *  `folder: Some(None)` explicitly unsets the folder (moves to root).
 */
export type MapMetaPatch_Serialize = {
	name: string | null;
	description: string | null;
	folder: string | null;
	settings: MapSettings | null;
	scoreBounds: ScoreBounds | null;
	extra: MapExtra | null;
	tags: {
		[key in string]: Tag;
	} | null;
	labels: string[] | null;
};
/**
 *  Per-map editor preferences. Controls Street View lookup behavior (official vs
 *  unofficial, camera type filters), export defaults, and metadata enrichment.
 */
export type MapSettings = {
	pointAlongRoad?: boolean;
	preferDirection?: string | null;
	preferOfficial?: boolean;
	preferHigherQuality?: boolean;
	onlyOfficial?: boolean;
	cameraTypes?: string[] | null;
	defaultPanoId?: boolean;
	exportZoom?: boolean;
	exportUnpanned?: boolean;
	searchRadius?: number | null;
	enrichMetadata?: boolean;
	enrichFields?: string[] | null;
	generatedLocationTag?: string | null;
};
/**
 *  Unified response for every mutation IPC. Bundles the store status, render delta,
 *  optional selection sync, optional newly-discovered extra-field keys, and optional
 *  updated tags. JS applies all of these atomically to stay in sync with the Rust state.
 *  `new_field_defs` carries the inferred/known field definitions for extra-field keys
 *  discovered for the first time in this mutation. JS merges them straight into the
 *  field-def registry, so field metadata is live without a reload.
 */
export type MutationResult_Serialize = {
	delta: RenderDelta_Serialize;
	selectionSync: SelectionSync | null;
	newFieldDefs: {
		[key in string]: ExtraFieldDef;
	} | null;
	tags: {
		[key in number]: Tag;
	} | null;
} & StoreStatus;
/**  Metadata for a user-installed plugin, read from `plugins/{id}/manifest.json`. */
export type PluginManifest = {
	id: string;
	name: string;
	description: string;
	icon: string;
	main: string;
};
/**
 *  GeoJSON-like polygon geometry. `coordinates` is the primary polygon (outer ring +
 *  optional holes). `extra_polygons` allows multipolygon selections (e.g., from GeoJSON import).
 */
export type PolygonGeometry = {
	coordinates: (([
		number,
		number
	])[])[];
	extraPolygons?: ((([
		number,
		number
	])[])[])[] | null;
	properties?: any | null;
};
/**
 *  Incremental render update sent to JS after a mutation. Contains adds, position/heading
 *  patches, swap-removals, and color patches (for selection overlay changes).
 *  `full_reset` signals JS to discard all cell data and re-fetch via `store_fill_render_file`.
 */
export type RenderDelta_Serialize = {
	added: RenderEntry[];
	updated: RenderPatchEntry[];
	removed: CellRemoval[];
	colorPatches: ColorPatchEntry[];
	fullReset?: boolean;
};
/**  A newly-added marker to a render cell: position, heading, and base color. */
export type RenderEntry = {
	cell: string;
	id: number;
	lng: number;
	lat: number;
	heading: number;
	r: number;
	g: number;
	b: number;
	a: number;
};
/**  Partial update to an existing marker within its cell (position and/or heading changed). */
export type RenderPatchEntry = {
	cell: string;
	cellIndex: number;
	lng: number | null;
	lat: number | null;
	heading: number | null;
};
/**
 *  Parameters for a full render rebuild. `marker_style` ("arrow" or "pin") determines
 *  whether heading angles are written. The bounding box fields are currently unused
 *  (no viewport culling -- all locations are rendered).
 */
export type RenderRequest = {
	west?: number;
	south?: number;
	east?: number;
	north?: number;
	selectedIds?: number[] | null;
	markerStyle?: string;
};
/**
 *  Inbound payload for creating a session. `order` is the frozen worklist (must be non-empty);
 *  the cursor starts at its first id and `reviewed` starts empty.
 */
export type ReviewCreate = {
	mapId: string;
	name: string;
	sourceKey: string;
	sourceProps: any;
	order: number[];
};
/**
 *  A review session as returned to the frontend. `order`/`reviewed` are decoded from the
 *  JSON-text columns; `source_props` is the originating `SelectionProps` (opaque here).
 */
export type ReviewSession = {
	id: string;
	mapId: string;
	name: string;
	sourceKey: string;
	sourceProps: any;
	order: number[];
	reviewed: number[];
	cursorId: number;
	status: string;
	createdAt: string;
	updatedAt: string;
};
/**
 *  Partial update. Any `Some` field is written; `None` leaves the column untouched.
 *  `ordering`/`reviewed` carry the full replacement arrays (used by reconciliation pruning).
 */
export type ReviewUpdate = {
	id: string;
	cursorId: number | null;
	reviewed: number[] | null;
	ordering: number[] | null;
	status: string | null;
};
/**  Result of `store_save_dirty`: how many bytes were written to the delta file. */
export type SaveResult = {
	savedChunks: number;
};
/**
 *  Score bounding box: either `"auto"` (computed from locations) or an
 *  explicit `[south, west, north, east]` rectangle.
 */
export type ScoreBounds = string | [
	number,
	number,
	number,
	number
];
/**  A panorama visit record as returned to the frontend. */
export type SeenEntry = {
	id: number;
	panoId: string;
	lat: number;
	lng: number;
	heading: number;
	pitch: number;
	zoom: number;
	enteredAt: number;
	mapId: string | null;
	locationId: number | null;
	countryCode: string | null;
	address: string | null;
	thumbnail: string | null;
};
/**
 *  Optional filters for seen-history queries. All fields are AND-combined.
 *  `search` does a substring match on the `address` column.
 */
export type SeenFilter = {
	country?: string | null;
	mapId?: string | null;
	search?: string | null;
};
/**
 *  Map id + display name pair for the "filter by map" dropdown.
 *  Name is resolved from the `maps` table when available, falling back to raw id.
 */
export type SeenMapInfo = {
	id: string;
	name: string;
};
/**
 *  Inbound payload for recording a new panorama visit. Same shape as `SeenEntry`
 *  minus the auto-assigned `id`.
 */
export type SeenWriteEntry = {
	panoId: string;
	lat: number;
	lng: number;
	heading: number;
	pitch: number;
	zoom: number;
	enteredAt: number;
	mapId: string | null;
	locationId: number | null;
	countryCode: string | null;
	address: string | null;
	thumbnail: string | null;
};
type Selection$1 = {
	key: string;
	color: [
		number,
		number,
		number
	];
	props: SelectionProps;
	/**  JS-only: cached resolved count for sidebar display. Rust never sets this. */
	count?: number | null;
};
/**  Input for `store_sync_selections`: selection criteria + display color. */
export type SelectionInput = {
	props: SelectionProps;
	color: [
		number,
		number,
		number
	];
};
/**
 *  Discriminated union of all selection types. Serialized with `{ "type": "..." }` tag
 *  for JS interop. Simple types (Tag, Untagged, PanoIds, etc.) resolve in O(N) with
 *   parallel batch scans. Composites (Intersection, Union, Invert) recursively resolve
 *  children. Duplicates uses a grid-accelerated spatial scan.
 */
export type SelectionProps = {
	type: "Locations";
	locations: number[];
	name: string | null;
} | {
	type: "Everything";
} | {
	type: "Polygon";
	polygon: PolygonGeometry;
	includeInformational: boolean;
} | {
	type: "Tag";
	tagId: number;
} | {
	type: "Untagged";
} | {
	type: "Unpanned";
} | {
	type: "PanoIds";
} | {
	type: "NotPanoIds";
} | {
	type: "Manual";
	locations: number[];
} | {
	type: "Duplicates";
	distance: number;
} | {
	type: "ValidationState";
	locations: number[];
	state: number;
} | {
	type: "Reviewed";
	locations: number[];
	sessionId: string;
	mode: string;
} | {
	type: "Intersection";
	selections: Selection$1[];
} | {
	type: "Union";
	selections: Selection$1[];
} | {
	type: "Invert";
	selections: Selection$1[];
} | {
	type: "Filter";
	field: string;
	op: string;
	value: any;
	value2?: any | null;
};
/**
 *  Selection bitmask sync payload. `bitmask` carries the packed per-cell bitmask bytes
 *  inline in the IPC response (no shared temp file → no clobber race under concurrent
 *  mutations). `None` when nothing changed. `counts` gives per-selection match counts.
 */
export type SelectionSync = {
	counts: number[];
	bitmask: number[] | null;
	selectedCount: number;
};
/**
 *  Metadata snapshot returned to JS after every mutation. JS uses `version` to
 *  detect stale responses and `canUndo`/`canRedo` for toolbar button state.
 *  `known_field_keys` lists every extra-field key that exists in location data
 *  on this map. Add-only within a session; seeded from `MapMeta.extra.fields`
 *  on map open.
 */
export type StoreStatus = {
	version: number;
	locationCount: number;
	canUndo: boolean;
	canRedo: boolean;
	tagCounts: {
		[key in number]: number;
	};
	knownFieldKeys: string[];
};
/**  Lightweight status for polling: count, version, and whether unsaved changes exist. */
export type SummaryResult = {
	locationCount: number;
	version: number;
	dirtyCount: number;
};
/**  Result of `store_sync_selections`: per-selection counts and the inline bitmask bytes. */
export type SyncSelectionsResult = {
	counts: number[];
	bitmask: number[] | null;
	selectedCount: number;
};
/**
 *  A user-defined label that can be applied to any number of locations.
 *
 *  Tags are stored in `MapMeta` and referenced by id in each `Location.tags`.
 *  The `count` field is maintained by callers during batch mutations, not by
 *  the overlay add/remove methods.
 */
export type Tag = {
	id: number;
	name: string;
	/**
	 *  Hex color string (e.g. "#3a7fc2"). Generated deterministically from
	 *  the tag name via `util::color_for_name` when not explicitly set.
	 */
	color: string;
	visible?: boolean;
	/**
	 *  Display order in the sidebar tag list. `None` for legacy tags
	 *  that predate ordered insertion.
	 */
	order?: number | null;
	/**
	 *  Number of locations currently carrying this tag. Denormalized for
	 *  fast sidebar display -- kept in sync by callers after batch edits.
	 */
	count?: number;
};
type Location$1 = Location_Serialize;
type Tag$1 = Tag;
export type ImportPreview = EditorImportPreview;
declare function createLocation(partial: Partial<Location$1> & {
	lat: number;
	lng: number;
}): Location$1;
export type WorkArea = "overview" | "location" | "duplicates" | "import" | "plugin" | "diff";
/** Variants that wrap children — derived as exactly those carrying a `selections` array. */
export type CompositeType = Extract<SelectionProps, {
	selections: Selection$1[];
}>["type"];
/** Composite variants that are flat groups (no negation). */
export type GroupType = Exclude<CompositeType, "Invert">;
declare enum ValidationState {
	Ok = 0,
	UpdateAvailable = 1,
	UpdateApplied = 2,
	NotFound = 3,
	PanoIdBroke = 4,
	Unofficial = 5,
	GoodcamAvailable = 6
}
export type FilterOp = "eq" | "neq" | "gt" | "lt" | "gte" | "lte" | "between" | "between_anyyear" | "between_anytime" | "has" | "nothas";
/** When a move target already holds a value, which field's value survives. */
export type MergeWinner = "from" | "to";
export type RenderDelta = RenderDelta_Serialize;
/** Parsed-but-not-committed import shown while `workArea === "import"`. */
export interface ImportStaging {
	preview: ImportPreview;
	source: "file" | "paste";
}
/** Ephemeral commit-diff overlay shown while `workArea === "diff"`. Position arrays are
 *  interleaved `[lng, lat]` f32; `diffMarkerVersion` bumps to rebuild the layers. */
export interface CommitDiffPreview {
	commitId: string;
	hash: string;
	counts: {
		added: number;
		removed: number;
		modified: number;
	};
	added: Float32Array;
	removed: Float32Array;
	modified: Float32Array;
}
export interface PruneResult {
	session: ReviewSession | null;
	cursorMoved: boolean;
}
declare function preloadModules(ids: string[]): Promise<void>;
declare function getAvailableExternals(): string[];
export interface EnrichFieldOption {
	key: string;
	label: string;
	/** Excluded from the default field set (null enrichFields); user must opt in. */
	defaultOff?: boolean;
}
declare function registerEnrichFields(fields: EnrichFieldOption[]): void;
export interface EnrichmentProvider {
	id: string;
	enrich(locations: Location$1[], enrichFields: string[] | null): Promise<Map<number, Record<string, unknown>>>;
	fieldDefs: Record<string, ExtraFieldDef>;
	/** When set, this provider is auto-invoked after patchLocationExtra writes any of these fields. */
	requires?: string[];
}
declare function registerEnrichmentProvider(provider: EnrichmentProvider): void;
declare function getFieldDef(key: string): ExtraFieldDef | undefined;
declare function getAllFieldDefs(): Record<string, ExtraFieldDef>;
/**
 * Command arguments.
 *
 * @since 1.0.0
 */
export type InvokeArgs = Record<string, unknown> | number[] | ArrayBuffer | Uint8Array;
/**
 * @since 2.0.0
 */
export interface InvokeOptions {
	headers: HeadersInit;
}
declare function invoke<T>(cmd: string, args?: InvokeArgs, options?: InvokeOptions): Promise<T>;
/**
 * @since 2.0.0
 */
export interface SpawnOptions {
	/** Current working directory. */
	cwd?: string;
	/** Environment variables. set to `null` to clear the process env. */
	env?: Record<string, string>;
	/**
	 * Character encoding for stdout/stderr
	 *
	 * @since 2.0.0
	 *  */
	encoding?: string;
}
/**
 * @since 2.0.0
 */
export interface ChildProcess<O extends IOPayload> {
	/** Exit code of the process. `null` if the process was terminated by a signal on Unix. */
	code: number | null;
	/** If the process was terminated by a signal, represents that signal. */
	signal: number | null;
	/** The data that the process wrote to `stdout`. */
	stdout: O;
	/** The data that the process wrote to `stderr`. */
	stderr: O;
}
declare class EventEmitter<E extends Record<string, any>> {
	/** @ignore */
	private eventListeners;
	/**
	 * Alias for `emitter.on(eventName, listener)`.
	 *
	 * @since 2.0.0
	 */
	addListener<N extends keyof E>(eventName: N, listener: (arg: E[typeof eventName]) => void): this;
	/**
	 * Alias for `emitter.off(eventName, listener)`.
	 *
	 * @since 2.0.0
	 */
	removeListener<N extends keyof E>(eventName: N, listener: (arg: E[typeof eventName]) => void): this;
	/**
	 * Adds the `listener` function to the end of the listeners array for the
	 * event named `eventName`. No checks are made to see if the `listener` has
	 * already been added. Multiple calls passing the same combination of `eventName`and `listener` will result in the `listener` being added, and called, multiple
	 * times.
	 *
	 * Returns a reference to the `EventEmitter`, so that calls can be chained.
	 *
	 * @since 2.0.0
	 */
	on<N extends keyof E>(eventName: N, listener: (arg: E[typeof eventName]) => void): this;
	/**
	 * Adds a **one-time**`listener` function for the event named `eventName`. The
	 * next time `eventName` is triggered, this listener is removed and then invoked.
	 *
	 * Returns a reference to the `EventEmitter`, so that calls can be chained.
	 *
	 * @since 2.0.0
	 */
	once<N extends keyof E>(eventName: N, listener: (arg: E[typeof eventName]) => void): this;
	/**
	 * Removes the all specified listener from the listener array for the event eventName
	 * Returns a reference to the `EventEmitter`, so that calls can be chained.
	 *
	 * @since 2.0.0
	 */
	off<N extends keyof E>(eventName: N, listener: (arg: E[typeof eventName]) => void): this;
	/**
	 * Removes all listeners, or those of the specified eventName.
	 *
	 * Returns a reference to the `EventEmitter`, so that calls can be chained.
	 *
	 * @since 2.0.0
	 */
	removeAllListeners<N extends keyof E>(event?: N): this;
	/**
	 * @ignore
	 * Synchronously calls each of the listeners registered for the event named`eventName`, in the order they were registered, passing the supplied arguments
	 * to each.
	 *
	 * @returns `true` if the event had listeners, `false` otherwise.
	 *
	 * @since 2.0.0
	 */
	emit<N extends keyof E>(eventName: N, arg: E[typeof eventName]): boolean;
	/**
	 * Returns the number of listeners listening to the event named `eventName`.
	 *
	 * @since 2.0.0
	 */
	listenerCount<N extends keyof E>(eventName: N): number;
	/**
	 * Adds the `listener` function to the _beginning_ of the listeners array for the
	 * event named `eventName`. No checks are made to see if the `listener` has
	 * already been added. Multiple calls passing the same combination of `eventName`and `listener` will result in the `listener` being added, and called, multiple
	 * times.
	 *
	 * Returns a reference to the `EventEmitter`, so that calls can be chained.
	 *
	 * @since 2.0.0
	 */
	prependListener<N extends keyof E>(eventName: N, listener: (arg: E[typeof eventName]) => void): this;
	/**
	 * Adds a **one-time**`listener` function for the event named `eventName` to the_beginning_ of the listeners array. The next time `eventName` is triggered, this
	 * listener is removed, and then invoked.
	 *
	 * Returns a reference to the `EventEmitter`, so that calls can be chained.
	 *
	 * @since 2.0.0
	 */
	prependOnceListener<N extends keyof E>(eventName: N, listener: (arg: E[typeof eventName]) => void): this;
}
declare class Child {
	/** The child process `pid`. */
	pid: number;
	constructor(pid: number);
	/**
	 * Writes `data` to the `stdin`.
	 *
	 * @param data The message to write, either a string or a byte array.
	 * @example
	 * ```typescript
	 * import { Command } from '@tauri-apps/plugin-shell';
	 * const command = Command.create('node');
	 * const child = await command.spawn();
	 * await child.write('message');
	 * await child.write([0, 1, 2, 3, 4, 5]);
	 * ```
	 *
	 * @returns A promise indicating the success or failure of the operation.
	 *
	 * @since 2.0.0
	 */
	write(data: IOPayload | number[]): Promise<void>;
	/**
	 * Kills the child process.
	 *
	 * @returns A promise indicating the success or failure of the operation.
	 *
	 * @since 2.0.0
	 */
	kill(): Promise<void>;
}
export interface CommandEvents {
	close: TerminatedPayload;
	error: string;
}
export interface OutputEvents<O extends IOPayload> {
	data: O;
}
declare class Command<O extends IOPayload> extends EventEmitter<CommandEvents> {
	/** @ignore Program to execute. */
	private readonly program;
	/** @ignore Program arguments */
	private readonly args;
	/** @ignore Spawn options. */
	private readonly options;
	/** Event emitter for the `stdout`. Emits the `data` event. */
	readonly stdout: EventEmitter<OutputEvents<O>>;
	/** Event emitter for the `stderr`. Emits the `data` event. */
	readonly stderr: EventEmitter<OutputEvents<O>>;
	/**
	 * @ignore
	 * Creates a new `Command` instance.
	 *
	 * @param program The program name to execute.
	 * It must be configured in your project's capabilities.
	 * @param args Program arguments.
	 * @param options Spawn options.
	 */
	private constructor();
	static create(program: string, args?: string | string[]): Command<string>;
	static create(program: string, args?: string | string[], options?: SpawnOptions & {
		encoding: "raw";
	}): Command<Uint8Array>;
	static create(program: string, args?: string | string[], options?: SpawnOptions): Command<string>;
	static sidecar(program: string, args?: string | string[]): Command<string>;
	static sidecar(program: string, args?: string | string[], options?: SpawnOptions & {
		encoding: "raw";
	}): Command<Uint8Array>;
	static sidecar(program: string, args?: string | string[], options?: SpawnOptions): Command<string>;
	/**
	 * Executes the command as a child process, returning a handle to it.
	 *
	 * @returns A promise resolving to the child process handle.
	 *
	 * @since 2.0.0
	 */
	spawn(): Promise<Child>;
	/**
	 * Executes the command as a child process, waiting for it to finish and collecting all of its output.
	 * @example
	 * ```typescript
	 * import { Command } from '@tauri-apps/plugin-shell';
	 * const output = await Command.create('echo', 'message').execute();
	 * assert(output.code === 0);
	 * assert(output.signal === null);
	 * assert(output.stdout === 'message');
	 * assert(output.stderr === '');
	 * ```
	 *
	 * @returns A promise resolving to the child process output.
	 *
	 * @since 2.0.0
	 */
	execute(): Promise<ChildProcess<O>>;
}
/**
 * Payload for the `Terminated` command event.
 */
export interface TerminatedPayload {
	/** Exit code of the process. `null` if the process was terminated by a signal on Unix. */
	code: number | null;
	/** If the process was terminated by a signal, represents that signal. */
	signal: number | null;
}
/** Event payload type */
export type IOPayload = string | Uint8Array;
/**
 * Extension filters for the file dialog.
 *
 * @since 2.0.0
 */
export interface DialogFilter {
	/** Filter name. */
	name: string;
	/**
	 * Extensions to filter, without a `.` prefix.
	 *
	 * **Note:** Mobile platforms have different APIs for filtering that may not support extensions.
	 * iOS: Extensions are supported in the document picker, but not in the media picker.
	 * Android: Extensions are not supported.
	 *
	 * For these platforms, MIME types are the primary way to filter files, as opposed to extensions.
	 * This means the string values here labeled as `extensions` may also be a MIME type.
	 * This property name of `extensions` is being kept for backwards compatibility, but this may be revisited to
	 * specify the difference between extension or MIME type filtering.
	 *
	 * @example
	 * ```typescript
	 * extensions: ['svg', 'png']
	 * ```
	 */
	extensions: string[];
}
/**
 * Options for the open dialog.
 *
 * @since 2.0.0
 */
export interface OpenDialogOptions {
	/** The title of the dialog window (desktop only). */
	title?: string;
	/**
	 * The filters of the dialog.
	 * On mobile platforms, if either:
	 * A) the {@linkcode pickerMode} is set to `media`, `image`, or `video`
	 * -- or --
	 * B) the filters include **only** either image or video mime types, the media picker will be displayed.
	 * Otherwise, the document picker will be displayed.
	 */
	filters?: DialogFilter[];
	/**
	 * Initial directory or file path.
	 * If it's a directory path, the dialog interface will change to that folder.
	 * If it's not an existing directory, the file name will be set to the dialog's file name input and the dialog will be set to the parent folder.
	 *
	 * On mobile the file name is always used on the dialog's file name input.
	 * If not provided, Android uses `(invalid).txt` as default file name.
	 */
	defaultPath?: string;
	/** Whether the dialog allows multiple selection or not. */
	multiple?: boolean;
	/** Whether the dialog is a directory selection or not. */
	directory?: boolean;
	/**
	 * If `directory` is true, indicates that it will be read recursively later.
	 * Defines whether subdirectories will be allowed on the scope or not.
	 */
	recursive?: boolean;
	/** Whether to allow creating directories in the dialog. Enabled by default. **macOS Only** */
	canCreateDirectories?: boolean;
	/**
	 * The preferred mode of the dialog.
	 * This is meant for mobile platforms (iOS and Android) which have distinct file and media pickers.
	 * If not provided, the dialog will automatically choose the best mode based on the MIME types or extensions of the {@linkcode filters}.
	 * On desktop, this option is ignored.
	 */
	pickerMode?: PickerMode;
	/**
	 * The file access mode of the dialog.
	 * If not provided, `copy` is used, which matches the behavior of the {@linkcode open} method before the introduction of this option.
	 *
	 * **Usage**
	 * If a file is opened with {@linkcode fileAccessMode: 'copy'}, it will be copied to the app's sandbox.
	 * This means the file can be read, edited, deleted, copied, or any other operation without any issues, since the file
	 * now belongs to the app.
	 * This also means that the caller has responsibility of deleting the file if this file is not meant to be retained
	 * in the app sandbox.
	 *
	 * If a file is opened with {@linkcode fileAccessMode: 'scoped'}, the file will remain in its original location
	 * and security-scoped access will be automatically managed by the system.
	 *
	 * **Note**
	 * This is specifically meant for document pickers on iOS or MacOS, in conjunction with [security scoped resources](https://developer.apple.com/documentation/foundation/nsurl/startaccessingsecurityscopedresource()).
	 *
	 * Why only document pickers, and not image or video pickers?
	 * The image and video pickers on iOS behave differently from the document pickers, and return [NSItemProvider](https://developer.apple.com/documentation/foundation/nsitemprovider) objects instead of file URLs.
	 * These are meant to be ephemeral (only available within the callback of the picker), and are not accessible outside of the callback.
	 * So for image and video pickers, the only way to access the file is to copy it to the app's sandbox, and this is the URL that is returned from this API.
	 * This means there is no provision for using `scoped` mode with image or video pickers.
	 * If an image or video picker is used, `copy` is always used.
	 */
	fileAccessMode?: FileAccessMode;
}
/**
 * Options for the save dialog.
 *
 * @since 2.0.0
 */
export interface SaveDialogOptions {
	/** The title of the dialog window (desktop only). */
	title?: string;
	/** The filters of the dialog. */
	filters?: DialogFilter[];
	/**
	 * Initial directory or file path.
	 * If it's a directory path, the dialog interface will change to that folder.
	 * If it's not an existing directory, the file name will be set to the dialog's file name input and the dialog will be set to the parent folder.
	 *
	 * On mobile the file name is always used on the dialog's file name input.
	 * If not provided, Android uses `(invalid).txt` as default file name.
	 */
	defaultPath?: string;
	/** Whether to allow creating directories in the dialog. Enabled by default. **macOS Only** */
	canCreateDirectories?: boolean;
}
/**
 * The preferred mode of the dialog.
 * This is meant for mobile platforms (iOS and Android) which have distinct file and media pickers.
 * On desktop, this option is ignored.
 * If not provided, the dialog will automatically choose the best mode based on the MIME types or extensions of the {@linkcode filters}.
 *
 * **Note:** This option is only supported on iOS 14 and above. This parameter is ignored on iOS 13 and below.
 */
export type PickerMode = "document" | "media" | "image" | "video";
/**
 * The file access mode of the dialog.
 *
 * - `copy`: copy/move the picked file to the app sandbox; no scoped access required.
 * - `scoped`: keep file in place; security-scoped access is automatically managed.
 *
 * **Note:** This option is only supported on iOS 14 and above. This parameter is ignored on iOS 13 and below.
 */
export type FileAccessMode = "copy" | "scoped";
export type OpenDialogReturn<T extends OpenDialogOptions> = T["directory"] extends true ? T["multiple"] extends true ? string[] | null : string | null : T["multiple"] extends true ? string[] | null : string | null;
declare function open$1<T extends OpenDialogOptions>(options?: T): Promise<OpenDialogReturn<T>>;
declare function save(options?: SaveDialogOptions): Promise<string | null>;
/** Payload type for each editor event. `void` means the event carries no payload. */
export interface EditorEventMap {
	"location:add": Location$1[];
	"location:remove": number[];
	"location:update": Partial<Location$1> & {
		id: number;
	};
	"selection:change": Selection$1[];
	"active:change": number | null;
	"map:open": MapData;
	"map:close": void;
}
export type EditorEvent = keyof EditorEventMap;
export type EventHandler<E extends EditorEvent> = (payload: EditorEventMap[E]) => void;
export interface SavedSelectionItem {
	props: SavedSelectionProps;
	color: [
		number,
		number,
		number
	];
}
export interface SavedSelection {
	id: string;
	name: string;
	items: SavedSelectionItem[];
	createdAt: number;
}
export type SavedSelectionProps = {
	type: "Everything";
} | {
	type: "Polygon";
	polygon: PolygonGeometry;
	includeInformational: boolean;
} | {
	type: "TagName";
	tagName: string;
} | {
	type: "Untagged";
} | {
	type: "Unpanned";
} | {
	type: "PanoIds";
} | {
	type: "NotPanoIds";
} | {
	type: "Duplicates";
	distance: number;
} | {
	type: "Filter";
	field: string;
	op: FilterOp;
	value: unknown;
	value2?: unknown;
} | {
	type: "Intersection";
	selections: SavedSelectionProps[];
} | {
	type: "Union";
	selections: SavedSelectionProps[];
} | {
	type: "Invert";
	selections: SavedSelectionProps[];
};
declare const MOVEMENT_MODES: {
	readonly moving: "Moving";
	readonly "no-move": "No Move";
	readonly nmpz: "NMPZ";
};
declare const SEEN_RESOLUTIONS: {
	readonly low: "Low (160x90)";
	readonly medium: "Medium (320x180)";
	readonly high: "High (640x360)";
};
declare const EXACT_DATE_FORMATS: {
	readonly date: "Date only";
	readonly datetime: "Date + time";
};
declare const DATE_TIMEZONES: {
	readonly location: "Location timezone";
	readonly utc: "UTC";
};
declare const MAP_LIST_FIELDS: {
	readonly locationCount: "Location count";
	readonly lastOpened: "Last opened";
	readonly created: "Date created";
};
declare const GEOCODE_PROVIDERS: {
	readonly local: "Local (offline)";
	readonly nominatim: "Nominatim (online)";
};
declare const TAG_VIEW_MODES: {
	readonly flat: "Flat";
	readonly tree: "Tree";
};
declare const BORDER_DETAILS: {
	readonly light: "Standard (bundled)";
	readonly medium: "High (~10MB)";
	readonly heavy: "Ultra (~46MB)";
};
declare const PREVIEW_ASPECT_RATIOS: {
	readonly "4 / 3": "4:3";
	readonly "16 / 10": "16:10";
	readonly "16 / 9": "16:9";
	readonly "21 / 9": "21:9";
	readonly "32 / 9": "32:9";
};
export type MovementMode = keyof typeof MOVEMENT_MODES;
export type ExactDateFormat = keyof typeof EXACT_DATE_FORMATS;
export type DateTimezone = keyof typeof DATE_TIMEZONES;
export type SeenResolution = keyof typeof SEEN_RESOLUTIONS;
export type MapListField = keyof typeof MAP_LIST_FIELDS;
export type GeocodeProvider = keyof typeof GEOCODE_PROVIDERS;
export type TagViewMode = keyof typeof TAG_VIEW_MODES;
export type BorderDetail = keyof typeof BORDER_DETAILS;
export type PreviewAspectRatio = keyof typeof PREVIEW_ASPECT_RATIOS;
declare const DEFAULTS: {
	showCameraBadges: boolean;
	showLinksControl: boolean;
	clickToGo: boolean;
	showRoadLabels: boolean;
	defaultMovementMode: MovementMode;
	showCar: boolean;
	showCrosshair: boolean;
	showCompass: boolean;
	showCompassTape: boolean;
	showZoom: boolean;
	showReturnToSpawn: boolean;
	showJumpButtons: boolean;
	showMapLinks: boolean;
	showCoordinateDisplay: boolean;
	showFullscreenButton: boolean;
	showPanoMetadata: boolean;
	exactDateFormat: ExactDateFormat;
	dateTimezone: DateTimezone;
	showNavArrow: boolean;
	showGroundArrow: boolean;
	hidePanoUI: boolean;
	fullscreenMap: boolean;
	showFullscreenMinimap: boolean;
	fullscreenMinimapScale: number;
	showFullscreenTagbar: boolean;
	customCss: string;
	enableSeen: boolean;
	enableSeenThumbnails: boolean;
	seenResolution: SeenResolution;
	mapPanSpeed: number;
	panoLookSpeed: number;
	slowModifier: number;
	showFps: boolean;
	mapListFields: MapListField[];
	geocodeProvider: GeocodeProvider;
	nominatimApiKey: string;
	panToImported: boolean;
	tagViewMode: TagViewMode;
	borderDetail: BorderDetail;
	previewAspectRatio: PreviewAspectRatio;
	savedSelections: SavedSelection[];
};
export type AppSettings = typeof DEFAULTS;
declare function setSetting<K extends keyof AppSettings>(key: K, value: AppSettings[K]): void;
declare function getSeenEntries(limit?: number, offset?: number, filter?: SeenFilter): Promise<SeenEntry[]>;
declare function getSeenCount(filter?: SeenFilter): Promise<number>;
declare function clearSeen(): Promise<void>;
declare function loadSeenPano(entry: SeenEntry): Promise<void>;
export interface ValidationProgress {
	progress: number;
	results: Map<ValidationState, Location$1[]>;
}
declare function validateLocations(locations: Location$1[], opts?: {
	signal?: AbortSignal;
	onProgress?: (p: ValidationProgress) => void;
}): Promise<Map<ValidationState, Location$1[]>>;
declare function mmaBufUrl(path: string): string;
export interface EnrichResult {
	metaSuccess: number[];
	metaFailed: number[];
	dateSuccess: number[];
	dateFailed: number[];
}
export interface LocationStore {
	locations: Map<number, Location$1>;
	onChange(cb: () => void): () => void;
	destroy(): void;
}
declare function createLocationStore(): Promise<LocationStore>;
declare const mma: {
	cmd: {
		writeTempFile: (name: string, content: string) => Promise<string>;
		readFile: (path: string) => Promise<string>;
		appReady: () => Promise<number>;
		getAppDataDir: () => Promise<string>;
		openDataFolder: () => Promise<null>;
		listUserPlugins: () => Promise<PluginManifest[]>;
		installPlugin: (id: string) => Promise<PluginManifest>;
		uninstallPlugin: (id: string) => Promise<null>;
		checkBorderFile: (level: string) => Promise<boolean>;
		downloadBorderFile: (level: string) => Promise<null>;
		borderLookup: (lat: number, lng: number, level: string) => Promise<{
			coordinates: (([
				number,
				number
			])[])[];
			extraPolygons?: ((([
				number,
				number
			])[])[])[] | null;
			properties?: any | null;
		} | null>;
		reverseGeocode: (lat: number, lng: number) => Promise<{
			city: string;
			admin: string;
			country: string;
			country_code: string;
		} | null>;
		storeOpenMap: (mapId: string) => Promise<StoreStatus>;
		storeCloseMap: () => Promise<null>;
		storeSaveDirty: () => Promise<SaveResult>;
		storeBakeAndSave: () => Promise<null>;
		storeGetSummary: () => Promise<SummaryResult>;
		storeListMaps: () => Promise<MapMeta[]>;
		storeGetMap: (id: string) => Promise<{
			meta: MapMeta;
		} | null>;
		storeCreateMap: (name: string, folder: string | null) => Promise<MapData>;
		storeDeleteMap: (id: string) => Promise<null>;
		storeUpdateMapMeta: (id: string, patch: MapMetaPatch_Deserialize) => Promise<null>;
		storeTouchMapOpened: (mapId: string) => Promise<null>;
		storeRenameFolder: (from: string, to: string) => Promise<null>;
		storeDeleteFolder: (name: string) => Promise<null>;
		storeDbTableInfo: () => Promise<DbTableInfo[]>;
		storeAddLocations: (locations: Location_Deserialize[]) => Promise<MutationResult_Serialize>;
		storeRemoveLocations: (ids: number[]) => Promise<MutationResult_Serialize>;
		storeUpdateLocations: (updates: [
			number,
			LocationPatch_Deserialize
		][], recordUndo: boolean | null) => Promise<MutationResult_Serialize>;
		storeSetActive: (id: number | null) => Promise<null>;
		storeGetLocation: (id: number) => Promise<{
			id: number;
			lat: number;
			lng: number;
			heading: number;
			pitch: number;
			zoom: number;
			panoId: string | null;
			flags: number;
			tags: number[];
			extra?: any | null;
			createdAt: string;
			modifiedAt?: string | null;
		} | null>;
		storeGetLocationsByIds: (ids: number[]) => Promise<Location_Serialize[]>;
		storeGetAllLocations: () => Promise<string>;
		storeCountryDistribution: (level: string) => Promise<[
			string,
			number
		][]>;
		storeLocationCount: () => Promise<number>;
		storeBounds: (selectedOnly: boolean) => Promise<[
			number,
			number,
			number,
			number
		] | null>;
		storeFindNearby: (lat: number, lng: number, radiusM: number) => Promise<Location_Serialize[]>;
		storeExtraFieldValues: (field: string) => Promise<string[]>;
		storeCreateTags: (names: string[]) => Promise<MutationResult_Serialize>;
		storeUpdateTag: (tagId: number, name: string | null, color: string | null) => Promise<MutationResult_Serialize>;
		storeDeleteTags: (tagIds: number[]) => Promise<MutationResult_Serialize>;
		storeReorderTags: (orderedIds: number[]) => Promise<MutationResult_Serialize>;
		storeUndo: () => Promise<MutationResult_Serialize>;
		storeRedo: () => Promise<MutationResult_Serialize>;
		storeResetUndo: () => Promise<null>;
		storeCommitDiff: () => Promise<[
			number,
			number,
			number
		]>;
		storeSyncSelections: (sels: SelectionInput[]) => Promise<SyncSelectionsResult>;
		storeGetSelectedIdsList: () => Promise<number[]>;
		storeResolveSelection: (props: SelectionProps) => Promise<number[]>;
		storeDuplicateGroups: (distance: number) => Promise<number[][]>;
		storeMergeDuplicates: (distance: number) => Promise<MutationResult_Serialize>;
		storeFillRenderFile: (req: RenderRequest) => Promise<string>;
		storeResolvePick: (cell: string, cellIndex: number) => Promise<number | null>;
		bulkImportPreview: (path: string) => Promise<ImportPreviewEntry[]>;
		bulkImportConfirm: (path: string, selectedIndices: number[]) => Promise<ImportedMapInfo[]>;
		storeImportPreview: (path: string) => Promise<EditorImportPreview>;
		storeImportPastePreview: (text: string) => Promise<EditorImportPreview>;
		storeImportFile: (droppedFields: string[], tagName: string | null) => Promise<EditorImportResult_Serialize>;
		storeExportJson: (opts: ExportOpts) => Promise<string>;
		storeExportCsv: (scope: number[] | null) => Promise<string>;
		storeExportGeojson: (scope: number[] | null, tagsJson: string) => Promise<string>;
		storeSaveExportFile: (srcPath: string, destPath: string) => Promise<null>;
		storeExportBulkZip: () => Promise<string>;
		storeDbClearTable: (table: string) => Promise<number>;
		storeDbStats: () => Promise<DbStats>;
		storeSeenWrite: (entry: SeenWriteEntry) => Promise<null>;
		storeSeenList: (limit: number, offset: number, filter: {
			country?: string | null;
			mapId?: string | null;
			search?: string | null;
		} | null) => Promise<SeenEntry[]>;
		storeSeenCount: (filter: {
			country?: string | null;
			mapId?: string | null;
			search?: string | null;
		} | null) => Promise<number>;
		storeSeenCountries: () => Promise<string[]>;
		storeSeenMaps: () => Promise<SeenMapInfo[]>;
		storeSeenClear: () => Promise<null>;
		storeReviewCreate: (session: ReviewCreate) => Promise<ReviewSession>;
		storeReviewGet: (mapId: string, sourceKey: string) => Promise<{
			id: string;
			mapId: string;
			name: string;
			sourceKey: string;
			sourceProps: any;
			order: number[];
			reviewed: number[];
			cursorId: number;
			status: string;
			createdAt: string;
			updatedAt: string;
		} | null>;
		storeReviewList: (mapId: string, status: string | null) => Promise<ReviewSession[]>;
		storeReviewUpdate: (update: ReviewUpdate) => Promise<null>;
		storeReviewDelete: (id: string) => Promise<null>;
		storeCreateCommit: (mapId: string, message: string | null) => Promise<string>;
		storeListCommits: (mapId: string) => Promise<CommitInfo[]>;
		storeCheckoutCommit: (mapId: string, commitId: string) => Promise<null>;
		storeGetCommitDelta: (mapId: string, commitId: string) => Promise<CommitDelta_Serialize>;
	};
	invoke: typeof invoke;
	shell: {
		Command: typeof Command;
	};
	dialog: {
		open: typeof open$1;
		save: typeof save;
	};
	registerPlugin: typeof registerPlugin;
	registerEnrichFields: typeof registerEnrichFields;
	registerEnrichmentProvider: typeof registerEnrichmentProvider;
	preloadModules: typeof preloadModules;
	getAvailableExternals: typeof getAvailableExternals;
	createLocationStore: typeof createLocationStore;
	getFieldDef: typeof getFieldDef;
	getAllFieldDefs: typeof getAllFieldDefs;
	createLocation: typeof createLocation;
	getGoogleMap: () => google.maps.Map | null;
	waitForGoogleMap: () => Promise<google.maps.Map>;
	setSetting: typeof setSetting;
	getSettings: () => {
		showCameraBadges: boolean;
		showLinksControl: boolean;
		clickToGo: boolean;
		showRoadLabels: boolean;
		defaultMovementMode: MovementMode;
		showCar: boolean;
		showCrosshair: boolean;
		showCompass: boolean;
		showCompassTape: boolean;
		showZoom: boolean;
		showReturnToSpawn: boolean;
		showJumpButtons: boolean;
		showMapLinks: boolean;
		showCoordinateDisplay: boolean;
		showFullscreenButton: boolean;
		showPanoMetadata: boolean;
		exactDateFormat: ExactDateFormat;
		dateTimezone: DateTimezone;
		showNavArrow: boolean;
		showGroundArrow: boolean;
		hidePanoUI: boolean;
		fullscreenMap: boolean;
		showFullscreenMinimap: boolean;
		fullscreenMinimapScale: number;
		showFullscreenTagbar: boolean;
		customCss: string;
		enableSeen: boolean;
		enableSeenThumbnails: boolean;
		seenResolution: SeenResolution;
		mapPanSpeed: number;
		panoLookSpeed: number;
		slowModifier: number;
		showFps: boolean;
		mapListFields: MapListField[];
		geocodeProvider: GeocodeProvider;
		nominatimApiKey: string;
		panToImported: boolean;
		tagViewMode: TagViewMode;
		borderDetail: BorderDetail;
		previewAspectRatio: PreviewAspectRatio;
		savedSelections: SavedSelection[];
	};
	on<E extends EditorEvent>(event: E, handler: EventHandler<E>): () => void;
	getSeenEntries: typeof getSeenEntries;
	getSeenCount: typeof getSeenCount;
	clearSeen: typeof clearSeen;
	loadSeenPano: typeof loadSeenPano;
	enrichAll: (opts?: Record<string, unknown>) => Promise<EnrichResult>;
	bulkPinToPano: (opts?: Record<string, unknown>) => Promise<number>;
	validateLocations: typeof validateLocations;
	needsEnrichment: (loc: Pick<Location$1, "extra">) => boolean;
	importPaste: (text: string) => Promise<EditorImportResult_Serialize[]>;
	importFile: (droppedFields: string[], tagName?: string) => Promise<EditorImportResult_Serialize>;
	mmaBufUrl: typeof mmaBufUrl;
	pruneSession(s: ReviewSession, removed: Set<number>): PruneResult;
	advance(s: ReviewSession): {
		session: ReviewSession;
		done: boolean;
	};
	retreat(s: ReviewSession): ReviewSession | null;
	reviewIndex(s: ReviewSession): number;
	isAtStart(s: ReviewSession): boolean;
	isCurrentReviewed(s: ReviewSession): boolean;
	useReviewSession(): ReviewSession | null;
	getReviewSession(): ReviewSession | null;
	beginReview(ids: number[], source?: Selection$1): Promise<void>;
	resumeReview(s: ReviewSession): Promise<void>;
	reviewNext(): Promise<void>;
	reviewPrev(): Promise<void>;
	reviewDelete(): Promise<void>;
	cancelReview(): void;
	deleteSession(id: string): Promise<void>;
	listSessions(status?: "active" | "done"): Promise<ReviewSession[]>;
	selectReviewSet(s: ReviewSession, mode: "reviewed" | "unreviewed"): Promise<void>;
	openMap: (id: string) => Promise<void>;
	closeMap: () => Promise<void>;
	invalidateMapList(): Promise<void>;
	getTagCounts(): Record<number, number>;
	refreshAfterMutation(): void;
	getVisibleTags(): Tag$1[];
	getImportPreviewPositions(): Float32Array<ArrayBuffer>;
	getCommitDiffPreview(): CommitDiffPreview | null;
	hasCommitDiff(): boolean;
	useCommitDiff(): {
		added: number;
		removed: number;
		modified: number;
	};
	getDirtyCount(): Promise<number>;
	scheduleSave(): void;
	flushSave(): Promise<void>;
	initStore(): Promise<void>;
	mapOpenMark(phase: string): void;
	getCurrentMapId(): string | null;
	getCurrentMap(): MapData | null;
	getKnownFieldKeys(): ReadonlySet<string>;
	getActiveLocation(): Location$1 | null;
	fetchAllLocations(): Promise<Location$1[]>;
	fetchLocation(id: number): Promise<Location$1 | null>;
	fetchLocationsByIds(ids: number[]): Promise<Location$1[]>;
	getSelections(): Selection$1[];
	getSelectedLocationIds(): Set<number>;
	syncSelections(): Promise<{
		ids: number[];
	}>;
	createMap(name: string, folder?: string | null): Promise<MapMeta>;
	deleteMap(id: string): Promise<void>;
	renameFolder(from: string, to: string): Promise<void>;
	moveMapToFolder(mapId: string, folder: string | null): Promise<void>;
	deleteFolder(name: string): Promise<void>;
	renameMap(id: string, name: string): Promise<void>;
	updateMapLabels(id: string, labels: string[]): Promise<void>;
	updateMapMeta(patch: MapMetaPatch): Promise<void>;
	setMapExtraFields(fields: Record<string, ExtraFieldDef>): Promise<void>;
	mutate(p: Promise<MutationResult_Serialize>): Promise<MutationResult_Serialize>;
	addLocations(locs: Location$1[], opts?: {
		hideInDelta?: boolean;
	}): Promise<void>;
	duplicateLocation(locId: number): Promise<number | null>;
	updateLocationNoUndo(id: number, patch: Partial<Location$1>): Promise<MutationResult_Serialize>;
	removeLocations(ids: Set<number>): Promise<void>;
	updateLocation(loc: Location$1, patch: Partial<Location$1>): Promise<void>;
	batchUpdateLocations(updates: {
		id: number;
		patch: Partial<Location$1>;
	}[]): Promise<void | MutationResult_Serialize>;
	renameField(from: string, to: string, winner?: MergeWinner): Promise<void>;
	deleteField(key: string): Promise<void>;
	patchLocationExtra(loc: Location$1, extraPatch: Record<string, unknown>, replace?: boolean): Promise<void>;
	isSelectionGhosted(key: string): boolean;
	toggleGhostSelection(key: string): Promise<void>;
	toggleGhostAllSelections(): Promise<void>;
	addSelections(props: SelectionProps[]): Promise<void>;
	removeSelections(keys: string[]): Promise<void>;
	resetSelections(): Promise<void>;
	selectIntersection(keys?: string[] | null): Promise<void>;
	selectUnion(keys?: string[] | null): Promise<void>;
	selectInverse(keys?: string[] | null): Promise<void>;
	toggleManualSelection(locationId: number): Promise<void>;
	selectRandomFromSelection(count: number): number;
	selectEverything(): Promise<void>;
	selectUntagged(): Promise<void>;
	selectUnpanned(): Promise<void>;
	selectPanoIds(): Promise<void>;
	selectNotPanoIds(): Promise<void>;
	selectDuplicates(distance: number): Promise<void>;
	previewDuplicateGroups(distance: number): Promise<number[][]>;
	mergeDuplicates(distance: number): Promise<void>;
	selectTag(tagId: number): Promise<void>;
	selectPolygon(polygon: PolygonGeometry, includeInformational?: boolean): Promise<void>;
	selectFilter(field: string, op: FilterOp, value: unknown, value2?: unknown): Promise<void>;
	updateFilterSelection(oldKey: string, props: SelectionProps): Promise<void>;
	setPolygonName(key: string, name: string): Promise<void>;
	setSelectionColors(entries: {
		key: string;
		color: [
			number,
			number,
			number
		];
	}[]): void;
	reorderSelection(fromKey: string, toKey: string, position: "before" | "after"): void;
	composeSelections(dragKey: string, dropKey: string, mode: GroupType, dragParent: string | null, dropParent: string | null): void;
	decomposeChild(parentKey: string, childKey: string): void;
	removeChildFromSelection(parentKey: string, childKey: string): void;
	toggleTagSelections(tagIds: number[]): void;
	useSelectedTagIds(): Set<number>;
	setActiveLocation(id: number | null, checkDuplicates?: boolean): Promise<void>;
	openDuplicateLocation(loc: Location$1): void;
	removeDuplicate(id: number): void;
	closeDuplicates(): void;
	setWorkArea(area: WorkArea): void;
	getWorkArea(): WorkArea;
	setPluginMode(pluginId: string): void;
	exitPluginMode(): void;
	createTags(names: string[]): Promise<Tag$1[]>;
	updateTags(patches: {
		id: number;
		patch: Partial<Tag$1>;
	}[]): Promise<void>;
	deleteTags(tagIds: number[]): Promise<void>;
	reorderTags(orderedIds: number[]): Promise<void>;
	addTagToLocations(tagId: number, locationIds: number[]): Promise<void>;
	removeTagFromLocations(tagId: number, locationIds: number[]): Promise<void>;
	removeTagFromAllLocations(tagId: number): Promise<void>;
	beginImportFromPath(path: string): Promise<void>;
	beginImportFile(): Promise<void>;
	beginImportPaste(text: string): Promise<void>;
	confirmImport(droppedFields: string[], tagName?: string): Promise<EditorImportResult_Serialize | null>;
	cancelImport(): void;
	undo(): Promise<void>;
	redo(): Promise<void>;
	getUndoRedoState(): {
		canUndo: boolean;
		canRedo: boolean;
	};
	commitMap(message?: string): Promise<string>;
	diffPositions(locs: {
		lat: number;
		lng: number;
	}[]): Float32Array;
	categorizeCommitDelta<T extends {
		id: number;
	}>(delta: {
		created: T[];
		removed: T[];
	}): {
		added: T[];
		removed: T[];
		modified: T[];
	};
	beginCommitDiffPreview(commit: CommitInfo): Promise<void>;
	endCommitDiffPreview(): void;
	checkoutCommit(commitId: string): Promise<void>;
	renderDeltaBus: {
		on: (fn: (delta: RenderDelta) => void) => () => void;
		emit: (delta: RenderDelta) => void;
	};
	selBitmaskBus: {
		on: (fn: (selColors: [
			number,
			number,
			number
		][], cellEntries: {
			cellChar: string;
			locCount: number;
			masks: Uint8Array[];
		}[], setIds: (ids: Set<number>) => void) => void) => () => void;
		emit: (selColors: [
			number,
			number,
			number
		][], cellEntries: {
			cellChar: string;
			locCount: number;
			masks: Uint8Array[];
		}[], setIds: (ids: Set<number>) => void) => void;
	};
	useMapList: () => MapMeta[];
	useTagCounts: () => Record<number, number>;
	useCurrentMap: () => MapData | null;
	useMapVersion: () => number;
	useSelectedLocationIds: () => Set<number>;
	useActiveLocation: () => Location_Serialize | null;
	useDuplicateLocations: () => Location_Serialize[];
	useWorkArea: () => WorkArea;
	useImportStaging: () => ImportStaging | null;
	useImportMarkerVersion: () => number;
	useCommitDiffPreview: () => CommitDiffPreview | null;
	useDiffMarkerVersion: () => number;
	useKnownFieldKeys: () => ReadonlySet<string>;
	useSelections: () => Selection$1[];
	useGhostedSelections: () => Set<string>;
	useActivePluginId: () => string | null;
	useUndoRedo: () => {
		canUndo: boolean;
		canRedo: boolean;
	};
	ready: boolean;
};
type MMA$1 = typeof mma;

export {
	MMA$1 as MMAApi,
	Plugin$1 as MMAPlugin,
};

export {};

declare global {
	const MMA: typeof mma;
}
