// Generated by dts-bundle-generator v9.5.1

/// <reference types="google.maps" />

import { ComponentType } from 'react';

export type CellRemoval = {
	cell: string;
	cellIndex: number;
	id: number;
};
export type ColorPatchEntry = {
	cell: string;
	cellIndex: number;
	r: number;
	g: number;
	b: number;
	a: number;
};
export type CommitBlobEntry = {
	geohash: string;
	blobHash: string;
	locationCount: number;
};
export type CommitInfo = {
	id: string;
	mapId: string;
	parentId: string | null;
	message: string | null;
	treeHash: string | null;
	added: number;
	removed: number;
	modified: number;
	locationCount: number;
	createdAt: string;
};
export type DbStats = {
	maps: number;
	locations: number;
	tags: number;
	commits: number;
	dbSizeBytes: number;
	journalMode: string;
	foreignKeys: boolean;
};
export type DbTableInfo = {
	name: string;
	rows: number;
};
export type EditorImportPreview = {
	locationCount: number;
	tags: Tag[];
	fields: FieldCount[];
	warnings: string[];
};
export type EditorImportResult_Serialize = {
	importedCount: number;
	warnings: string[];
} & MutationResult_Serialize;
export type ExportOpts = {
	exportZoom: boolean;
	exportUnpanned: boolean;
	exportExtras: boolean;
	scope: number[] | null;
	mapName: string;
	tagsJson: string;
	extraFieldsJson: string | null;
};
export type ExtraFieldDef = {
	type: ExtraFieldType;
	label?: string | null;
	values?: string[] | null;
	labels?: {
		[key in string]: string;
	} | null;
};
export type ExtraFieldType = "string" | "number" | "date" | "month" | "enum";
export type FieldCount = {
	key: string;
	count: number;
};
export type ImportPreviewEntry = {
	name: string;
	folder: string | null;
	locationCount: number;
	tagCount: number;
	warnings: string[];
};
export type ImportedMapInfo = {
	id: string;
	name: string;
	locationCount: number;
	tagCount: number;
};
export type LocationPatch_Deserialize = {
	lat?: number | null;
	lng?: number | null;
	heading?: number | null;
	pitch?: number | null;
	zoom?: number | null;
	panoId?: string | null;
	flags?: number | null;
	tags?: number[] | null;
	extra?: any | null;
	createdAt?: string | null;
	modifiedAt?: string | null;
};
export type Location_Deserialize = {
	id?: number;
	lat: number;
	lng: number;
	heading: number;
	pitch: number;
	zoom: number;
	panoId: string | null;
	flags: number;
	tags: number[];
	extra?: any | null;
	createdAt: string;
	modifiedAt?: string | null;
};
export type Location_Serialize = {
	id: number;
	lat: number;
	lng: number;
	heading: number;
	pitch: number;
	zoom: number;
	panoId: string | null;
	flags: number;
	tags: number[];
	extra?: any | null;
	createdAt: string;
	modifiedAt?: string | null;
};
export type MapData = {
	meta: MapMeta;
};
export type MapExtra = {
	fields?: {
		[key in string]: ExtraFieldDef;
	} | null;
};
export type MapMeta = {
	id: string;
	name: string;
	description: string;
	folder: string | null;
	settings: MapSettings;
	scoreBounds: ScoreBounds;
	extra: MapExtra;
	tags: {
		[key in string]: Tag;
	};
	labels: string[];
	locationCount: number;
	createdAt: string;
	updatedAt: string;
	lastOpenedAt: string | null;
};
export type MapMetaPatch = {
	name?: string | null;
	description?: string | null;
	folder?: string | null;
	settings?: MapSettings | null;
	scoreBounds?: ScoreBounds | null;
	extra?: MapExtra | null;
	tags?: {
		[key in string]: Tag;
	} | null;
	labels?: string[] | null;
};
export type MapSettings = {
	pointAlongRoad: boolean;
	preferDirection: number | null;
	preferOfficial: boolean;
	preferHigherQuality: boolean;
	onlyOfficial: boolean;
	cameraTypes: string[] | null;
	defaultPanoId: boolean;
	exportZoom: boolean;
	exportUnpanned: boolean;
	enrichMetadata: boolean;
	enrichFields: string[] | null;
	generatedLocationTag: string | null;
};
export type MutationResult_Serialize = {
	delta: RenderDelta_Serialize;
	selectionSync: SelectionSync | null;
	newFieldDefs: {
		[key in string]: ExtraFieldDef;
	} | null;
	tags: {
		[key in number]: Tag;
	} | null;
} & StoreStatus;
export type PluginManifest = {
	id: string;
	name: string;
	description: string;
	icon: string;
	main: string;
};
export type PolygonGeometry = {
	coordinates: (([
		number,
		number
	])[])[];
	extraPolygons?: ((([
		number,
		number
	])[])[])[] | null;
	properties?: any | null;
};
export type RenderDelta_Serialize = {
	added: RenderEntry[];
	updated: RenderPatchEntry[];
	removed: CellRemoval[];
	colorPatches: ColorPatchEntry[];
	fullReset?: boolean;
};
export type RenderEntry = {
	cell: string;
	id: number;
	lng: number;
	lat: number;
	heading: number;
	r: number;
	g: number;
	b: number;
	a: number;
};
export type RenderPatchEntry = {
	cell: string;
	cellIndex: number;
	lng: number | null;
	lat: number | null;
	heading: number | null;
};
export type RenderRequest = {
	west?: number;
	south?: number;
	east?: number;
	north?: number;
	selectedIds?: number[] | null;
	markerStyle?: string;
};
export type SaveResult = {
	savedChunks: number;
};
export type ScoreBounds = string | [
	number,
	number,
	number,
	number
];
export type SeenEntry = {
	id: number;
	panoId: string;
	lat: number;
	lng: number;
	heading: number;
	pitch: number;
	zoom: number;
	enteredAt: number;
	mapId: string | null;
	locationId: number | null;
	countryCode: string | null;
	address: string | null;
	thumbnail: string | null;
};
export type SeenFilter = {
	country?: string | null;
	mapId?: string | null;
	search?: string | null;
};
export type SeenMapInfo = {
	id: string;
	name: string;
};
export type SeenWriteEntry = {
	panoId: string;
	lat: number;
	lng: number;
	heading: number;
	pitch: number;
	zoom: number;
	enteredAt: number;
	mapId: string | null;
	locationId: number | null;
	countryCode: string | null;
	address: string | null;
	thumbnail: string | null;
};
type Selection$1 = {
	key: string;
	color: [
		number,
		number,
		number
	];
	props: SelectionProps;
	/**  JS-only: cached resolved count for sidebar display. Rust never sets this. */
	count?: number | null;
};
export type SelectionInput = {
	props: SelectionProps;
	color: [
		number,
		number,
		number
	];
};
export type SelectionProps = {
	type: "Locations";
	locations: number[];
	name: string | null;
} | {
	type: "Everything";
} | {
	type: "Polygon";
	polygon: PolygonGeometry;
	includeInformational: boolean;
} | {
	type: "Tag";
	tagId: number;
} | {
	type: "Untagged";
} | {
	type: "Unpanned";
} | {
	type: "PanoIds";
} | {
	type: "NotPanoIds";
} | {
	type: "Manual";
	locations: number[];
} | {
	type: "Duplicates";
	distance: number;
} | {
	type: "ValidationState";
	locations: number[];
	state: number;
} | {
	type: "Intersection";
	selections: Selection$1[];
} | {
	type: "Union";
	selections: Selection$1[];
} | {
	type: "Invert";
	selections: Selection$1[];
} | {
	type: "Filter";
	field: string;
	op: string;
	value: any;
	value2: any | null;
};
export type SelectionResult = {
	key: string;
	count: number;
	selectionVersion: number;
};
export type SelectionSummary = {
	key: string;
	color: [
		number,
		number,
		number
	];
	type: string;
	count: number;
};
export type SelectionSync = {
	counts: number[];
	patchFile: string | null;
	selectedCount: number;
};
export type StoreStatus = {
	version: number;
	locationCount: number;
	canUndo: boolean;
	canRedo: boolean;
	tagCounts: {
		[key in number]: number;
	};
};
export type SummaryResult = {
	locationCount: number;
	version: number;
	dirtyCount: number;
};
export type SyncSelectionsResult = {
	counts: number[];
	patchFile: string | null;
	selectedCount: number;
};
export type Tag = {
	id: number;
	name: string;
	color: string;
	visible?: boolean;
	order?: number | null;
	count?: number;
};
type Location$1 = Location_Serialize;
type Tag$1 = Tag;
declare function createLocation(partial: Partial<Location$1> & {
	lat: number;
	lng: number;
}): Location$1;
export type WorkArea = "overview" | "location" | "duplicates" | "import" | "plugin";
export interface PluginSettingDef {
	key: string;
	label: string;
	type: "boolean" | "string" | "number";
	default: unknown;
}
interface Plugin$1 {
	id: string;
	name: string;
	description?: string;
	icon: string;
	comingSoon?: boolean;
	settings?: PluginSettingDef[];
	activate(): void | (() => void);
	modal?: ComponentType<{
		onClose: () => void;
	}>;
	sidebar?: ComponentType<{
		onClose: () => void;
	}>;
	locationPanel?: ComponentType;
}
export type PluginBehavior = Partial<Plugin$1> & {
	activate(): void | (() => void);
};
declare function registerPlugin(plugin: Plugin$1 | PluginBehavior): void;
export interface EnrichFieldOption {
	key: string;
	label: string;
}
declare function registerEnrichFields(fields: EnrichFieldOption[]): void;
export interface EnrichmentProvider {
	id: string;
	enrich(locations: Location$1[], enrichFields: string[] | null): Promise<Map<number, Record<string, unknown>>>;
	fieldDefs: Record<string, ExtraFieldDef>;
}
declare function registerEnrichmentProvider(provider: EnrichmentProvider): void;
/**
 * Command arguments.
 *
 * @since 1.0.0
 */
export type InvokeArgs = Record<string, unknown> | number[] | ArrayBuffer | Uint8Array;
/**
 * @since 2.0.0
 */
export interface InvokeOptions {
	headers: HeadersInit;
}
declare function invoke<T>(cmd: string, args?: InvokeArgs, options?: InvokeOptions): Promise<T>;
/**
 * @since 2.0.0
 */
export interface SpawnOptions {
	/** Current working directory. */
	cwd?: string;
	/** Environment variables. set to `null` to clear the process env. */
	env?: Record<string, string>;
	/**
	 * Character encoding for stdout/stderr
	 *
	 * @since 2.0.0
	 *  */
	encoding?: string;
}
/**
 * @since 2.0.0
 */
export interface ChildProcess<O extends IOPayload> {
	/** Exit code of the process. `null` if the process was terminated by a signal on Unix. */
	code: number | null;
	/** If the process was terminated by a signal, represents that signal. */
	signal: number | null;
	/** The data that the process wrote to `stdout`. */
	stdout: O;
	/** The data that the process wrote to `stderr`. */
	stderr: O;
}
declare class EventEmitter<E extends Record<string, any>> {
	/** @ignore */
	private eventListeners;
	/**
	 * Alias for `emitter.on(eventName, listener)`.
	 *
	 * @since 2.0.0
	 */
	addListener<N extends keyof E>(eventName: N, listener: (arg: E[typeof eventName]) => void): this;
	/**
	 * Alias for `emitter.off(eventName, listener)`.
	 *
	 * @since 2.0.0
	 */
	removeListener<N extends keyof E>(eventName: N, listener: (arg: E[typeof eventName]) => void): this;
	/**
	 * Adds the `listener` function to the end of the listeners array for the
	 * event named `eventName`. No checks are made to see if the `listener` has
	 * already been added. Multiple calls passing the same combination of `eventName`and `listener` will result in the `listener` being added, and called, multiple
	 * times.
	 *
	 * Returns a reference to the `EventEmitter`, so that calls can be chained.
	 *
	 * @since 2.0.0
	 */
	on<N extends keyof E>(eventName: N, listener: (arg: E[typeof eventName]) => void): this;
	/**
	 * Adds a **one-time**`listener` function for the event named `eventName`. The
	 * next time `eventName` is triggered, this listener is removed and then invoked.
	 *
	 * Returns a reference to the `EventEmitter`, so that calls can be chained.
	 *
	 * @since 2.0.0
	 */
	once<N extends keyof E>(eventName: N, listener: (arg: E[typeof eventName]) => void): this;
	/**
	 * Removes the all specified listener from the listener array for the event eventName
	 * Returns a reference to the `EventEmitter`, so that calls can be chained.
	 *
	 * @since 2.0.0
	 */
	off<N extends keyof E>(eventName: N, listener: (arg: E[typeof eventName]) => void): this;
	/**
	 * Removes all listeners, or those of the specified eventName.
	 *
	 * Returns a reference to the `EventEmitter`, so that calls can be chained.
	 *
	 * @since 2.0.0
	 */
	removeAllListeners<N extends keyof E>(event?: N): this;
	/**
	 * @ignore
	 * Synchronously calls each of the listeners registered for the event named`eventName`, in the order they were registered, passing the supplied arguments
	 * to each.
	 *
	 * @returns `true` if the event had listeners, `false` otherwise.
	 *
	 * @since 2.0.0
	 */
	emit<N extends keyof E>(eventName: N, arg: E[typeof eventName]): boolean;
	/**
	 * Returns the number of listeners listening to the event named `eventName`.
	 *
	 * @since 2.0.0
	 */
	listenerCount<N extends keyof E>(eventName: N): number;
	/**
	 * Adds the `listener` function to the _beginning_ of the listeners array for the
	 * event named `eventName`. No checks are made to see if the `listener` has
	 * already been added. Multiple calls passing the same combination of `eventName`and `listener` will result in the `listener` being added, and called, multiple
	 * times.
	 *
	 * Returns a reference to the `EventEmitter`, so that calls can be chained.
	 *
	 * @since 2.0.0
	 */
	prependListener<N extends keyof E>(eventName: N, listener: (arg: E[typeof eventName]) => void): this;
	/**
	 * Adds a **one-time**`listener` function for the event named `eventName` to the_beginning_ of the listeners array. The next time `eventName` is triggered, this
	 * listener is removed, and then invoked.
	 *
	 * Returns a reference to the `EventEmitter`, so that calls can be chained.
	 *
	 * @since 2.0.0
	 */
	prependOnceListener<N extends keyof E>(eventName: N, listener: (arg: E[typeof eventName]) => void): this;
}
declare class Child {
	/** The child process `pid`. */
	pid: number;
	constructor(pid: number);
	/**
	 * Writes `data` to the `stdin`.
	 *
	 * @param data The message to write, either a string or a byte array.
	 * @example
	 * ```typescript
	 * import { Command } from '@tauri-apps/plugin-shell';
	 * const command = Command.create('node');
	 * const child = await command.spawn();
	 * await child.write('message');
	 * await child.write([0, 1, 2, 3, 4, 5]);
	 * ```
	 *
	 * @returns A promise indicating the success or failure of the operation.
	 *
	 * @since 2.0.0
	 */
	write(data: IOPayload | number[]): Promise<void>;
	/**
	 * Kills the child process.
	 *
	 * @returns A promise indicating the success or failure of the operation.
	 *
	 * @since 2.0.0
	 */
	kill(): Promise<void>;
}
export interface CommandEvents {
	close: TerminatedPayload;
	error: string;
}
export interface OutputEvents<O extends IOPayload> {
	data: O;
}
declare class Command<O extends IOPayload> extends EventEmitter<CommandEvents> {
	/** @ignore Program to execute. */
	private readonly program;
	/** @ignore Program arguments */
	private readonly args;
	/** @ignore Spawn options. */
	private readonly options;
	/** Event emitter for the `stdout`. Emits the `data` event. */
	readonly stdout: EventEmitter<OutputEvents<O>>;
	/** Event emitter for the `stderr`. Emits the `data` event. */
	readonly stderr: EventEmitter<OutputEvents<O>>;
	/**
	 * @ignore
	 * Creates a new `Command` instance.
	 *
	 * @param program The program name to execute.
	 * It must be configured in your project's capabilities.
	 * @param args Program arguments.
	 * @param options Spawn options.
	 */
	private constructor();
	static create(program: string, args?: string | string[]): Command<string>;
	static create(program: string, args?: string | string[], options?: SpawnOptions & {
		encoding: "raw";
	}): Command<Uint8Array>;
	static create(program: string, args?: string | string[], options?: SpawnOptions): Command<string>;
	static sidecar(program: string, args?: string | string[]): Command<string>;
	static sidecar(program: string, args?: string | string[], options?: SpawnOptions & {
		encoding: "raw";
	}): Command<Uint8Array>;
	static sidecar(program: string, args?: string | string[], options?: SpawnOptions): Command<string>;
	/**
	 * Executes the command as a child process, returning a handle to it.
	 *
	 * @returns A promise resolving to the child process handle.
	 *
	 * @since 2.0.0
	 */
	spawn(): Promise<Child>;
	/**
	 * Executes the command as a child process, waiting for it to finish and collecting all of its output.
	 * @example
	 * ```typescript
	 * import { Command } from '@tauri-apps/plugin-shell';
	 * const output = await Command.create('echo', 'message').execute();
	 * assert(output.code === 0);
	 * assert(output.signal === null);
	 * assert(output.stdout === 'message');
	 * assert(output.stderr === '');
	 * ```
	 *
	 * @returns A promise resolving to the child process output.
	 *
	 * @since 2.0.0
	 */
	execute(): Promise<ChildProcess<O>>;
}
/**
 * Payload for the `Terminated` command event.
 */
export interface TerminatedPayload {
	/** Exit code of the process. `null` if the process was terminated by a signal on Unix. */
	code: number | null;
	/** If the process was terminated by a signal, represents that signal. */
	signal: number | null;
}
/** Event payload type */
export type IOPayload = string | Uint8Array;
/**
 * Extension filters for the file dialog.
 *
 * @since 2.0.0
 */
export interface DialogFilter {
	/** Filter name. */
	name: string;
	/**
	 * Extensions to filter, without a `.` prefix.
	 *
	 * **Note:** Mobile platforms have different APIs for filtering that may not support extensions.
	 * iOS: Extensions are supported in the document picker, but not in the media picker.
	 * Android: Extensions are not supported.
	 *
	 * For these platforms, MIME types are the primary way to filter files, as opposed to extensions.
	 * This means the string values here labeled as `extensions` may also be a MIME type.
	 * This property name of `extensions` is being kept for backwards compatibility, but this may be revisited to
	 * specify the difference between extension or MIME type filtering.
	 *
	 * @example
	 * ```typescript
	 * extensions: ['svg', 'png']
	 * ```
	 */
	extensions: string[];
}
/**
 * Options for the open dialog.
 *
 * @since 2.0.0
 */
export interface OpenDialogOptions {
	/** The title of the dialog window (desktop only). */
	title?: string;
	/**
	 * The filters of the dialog.
	 * On mobile platforms, if either:
	 * A) the {@linkcode pickerMode} is set to `media`, `image`, or `video`
	 * -- or --
	 * B) the filters include **only** either image or video mime types, the media picker will be displayed.
	 * Otherwise, the document picker will be displayed.
	 */
	filters?: DialogFilter[];
	/**
	 * Initial directory or file path.
	 * If it's a directory path, the dialog interface will change to that folder.
	 * If it's not an existing directory, the file name will be set to the dialog's file name input and the dialog will be set to the parent folder.
	 *
	 * On mobile the file name is always used on the dialog's file name input.
	 * If not provided, Android uses `(invalid).txt` as default file name.
	 */
	defaultPath?: string;
	/** Whether the dialog allows multiple selection or not. */
	multiple?: boolean;
	/** Whether the dialog is a directory selection or not. */
	directory?: boolean;
	/**
	 * If `directory` is true, indicates that it will be read recursively later.
	 * Defines whether subdirectories will be allowed on the scope or not.
	 */
	recursive?: boolean;
	/** Whether to allow creating directories in the dialog. Enabled by default. **macOS Only** */
	canCreateDirectories?: boolean;
	/**
	 * The preferred mode of the dialog.
	 * This is meant for mobile platforms (iOS and Android) which have distinct file and media pickers.
	 * If not provided, the dialog will automatically choose the best mode based on the MIME types or extensions of the {@linkcode filters}.
	 * On desktop, this option is ignored.
	 */
	pickerMode?: PickerMode;
	/**
	 * The file access mode of the dialog.
	 * If not provided, `copy` is used, which matches the behavior of the {@linkcode open} method before the introduction of this option.
	 *
	 * **Usage**
	 * If a file is opened with {@linkcode fileAccessMode: 'copy'}, it will be copied to the app's sandbox.
	 * This means the file can be read, edited, deleted, copied, or any other operation without any issues, since the file
	 * now belongs to the app.
	 * This also means that the caller has responsibility of deleting the file if this file is not meant to be retained
	 * in the app sandbox.
	 *
	 * If a file is opened with {@linkcode fileAccessMode: 'scoped'}, the file will remain in its original location
	 * and security-scoped access will be automatically managed by the system.
	 *
	 * **Note**
	 * This is specifically meant for document pickers on iOS or MacOS, in conjunction with [security scoped resources](https://developer.apple.com/documentation/foundation/nsurl/startaccessingsecurityscopedresource()).
	 *
	 * Why only document pickers, and not image or video pickers?
	 * The image and video pickers on iOS behave differently from the document pickers, and return [NSItemProvider](https://developer.apple.com/documentation/foundation/nsitemprovider) objects instead of file URLs.
	 * These are meant to be ephemeral (only available within the callback of the picker), and are not accessible outside of the callback.
	 * So for image and video pickers, the only way to access the file is to copy it to the app's sandbox, and this is the URL that is returned from this API.
	 * This means there is no provision for using `scoped` mode with image or video pickers.
	 * If an image or video picker is used, `copy` is always used.
	 */
	fileAccessMode?: FileAccessMode;
}
/**
 * Options for the save dialog.
 *
 * @since 2.0.0
 */
export interface SaveDialogOptions {
	/** The title of the dialog window (desktop only). */
	title?: string;
	/** The filters of the dialog. */
	filters?: DialogFilter[];
	/**
	 * Initial directory or file path.
	 * If it's a directory path, the dialog interface will change to that folder.
	 * If it's not an existing directory, the file name will be set to the dialog's file name input and the dialog will be set to the parent folder.
	 *
	 * On mobile the file name is always used on the dialog's file name input.
	 * If not provided, Android uses `(invalid).txt` as default file name.
	 */
	defaultPath?: string;
	/** Whether to allow creating directories in the dialog. Enabled by default. **macOS Only** */
	canCreateDirectories?: boolean;
}
/**
 * The preferred mode of the dialog.
 * This is meant for mobile platforms (iOS and Android) which have distinct file and media pickers.
 * On desktop, this option is ignored.
 * If not provided, the dialog will automatically choose the best mode based on the MIME types or extensions of the {@linkcode filters}.
 *
 * **Note:** This option is only supported on iOS 14 and above. This parameter is ignored on iOS 13 and below.
 */
export type PickerMode = "document" | "media" | "image" | "video";
/**
 * The file access mode of the dialog.
 *
 * - `copy`: copy/move the picked file to the app sandbox; no scoped access required.
 * - `scoped`: keep file in place; security-scoped access is automatically managed.
 *
 * **Note:** This option is only supported on iOS 14 and above. This parameter is ignored on iOS 13 and below.
 */
export type FileAccessMode = "copy" | "scoped";
export type OpenDialogReturn<T extends OpenDialogOptions> = T["directory"] extends true ? T["multiple"] extends true ? string[] | null : string | null : T["multiple"] extends true ? string[] | null : string | null;
declare function open$1<T extends OpenDialogOptions>(options?: T): Promise<OpenDialogReturn<T>>;
declare function save(options?: SaveDialogOptions): Promise<string | null>;
export type EditorEvent = "location:add" | "location:remove" | "location:update" | "selection:change" | "map:open" | "map:close";
declare enum ValidationState {
	Ok = 0,
	UpdateAvailable = 1,
	UpdateApplied = 2,
	NotFound = 3,
	PanoIdBroke = 4,
	Unofficial = 5,
	GoodcamAvailable = 6
}
export type FilterOp = "eq" | "neq" | "gt" | "lt" | "gte" | "lte" | "between" | "has" | "nothas";
export interface SavedSelectionItem {
	props: SavedSelectionProps;
	color: [
		number,
		number,
		number
	];
}
export interface SavedSelection {
	id: string;
	name: string;
	items: SavedSelectionItem[];
	createdAt: number;
}
export type SavedSelectionProps = {
	type: "Everything";
} | {
	type: "Polygon";
	polygon: PolygonGeometry;
	includeInformational: boolean;
} | {
	type: "TagName";
	tagName: string;
} | {
	type: "Untagged";
} | {
	type: "Unpanned";
} | {
	type: "PanoIds";
} | {
	type: "NotPanoIds";
} | {
	type: "Duplicates";
	distance: number;
} | {
	type: "Filter";
	field: string;
	op: FilterOp;
	value: unknown;
	value2?: unknown;
} | {
	type: "Intersection";
	selections: SavedSelectionProps[];
} | {
	type: "Union";
	selections: SavedSelectionProps[];
} | {
	type: "Invert";
	selections: SavedSelectionProps[];
};
export type MovementMode = "moving" | "no-move" | "nmpz";
export type ExactDateFormat = "date" | "datetime";
export type DateTimezone = "location" | "utc";
export type SeenResolution = "low" | "medium" | "high";
export type MapListField = "locationCount" | "lastOpened" | "created";
export type GeocodeProvider = "local" | "nominatim";
export type TagViewMode = "flat" | "tree";
export interface AppSettings {
	showCameraBadges: boolean;
	showLinksControl: boolean;
	clickToGo: boolean;
	showRoadLabels: boolean;
	defaultMovementMode: MovementMode;
	showCar: boolean;
	showCrosshair: boolean;
	showCompass: boolean;
	showZoom: boolean;
	showReturnToSpawn: boolean;
	showJumpButtons: boolean;
	showMapLinks: boolean;
	showCoordinateDisplay: boolean;
	showFullscreenButton: boolean;
	showPanoMetadata: boolean;
	showExactDate: boolean;
	exactDateFormat: ExactDateFormat;
	dateTimezone: DateTimezone;
	showNavArrow: boolean;
	showGroundArrow: boolean;
	hidePanoUI: boolean;
	fullscreenMap: boolean;
	showFullscreenMinimap: boolean;
	showFullscreenTagbar: boolean;
	customCss: string;
	enableSeen: boolean;
	enableSeenThumbnails: boolean;
	seenResolution: SeenResolution;
	mapPanSpeed: number;
	mapZoomSpeed: number;
	panoLookSpeed: number;
	slowModifier: number;
	showFps: boolean;
	mapListFields: MapListField[];
	geocodeProvider: GeocodeProvider;
	nominatimApiKey: string;
	tagViewMode: TagViewMode;
	savedSelections: SavedSelection[];
}
declare function setSetting<K extends keyof AppSettings>(key: K, value: AppSettings[K]): void;
declare function getSeenEntries(limit?: number, offset?: number, filter?: SeenFilter): Promise<SeenEntry[]>;
declare function getSeenCount(filter?: SeenFilter): Promise<number>;
declare function clearSeen(): Promise<void>;
declare function loadSeenPano(entry: SeenEntry): void;
export interface ValidationProgress {
	progress: number;
	results: Map<ValidationState, Location$1[]>;
}
declare function validateLocations(locations: Location$1[], opts?: {
	signal?: AbortSignal;
	onProgress?: (p: ValidationProgress) => void;
}): Promise<Map<ValidationState, Location$1[]>>;
export interface EnrichResult {
	metaSuccess: number[];
	metaFailed: number[];
	dateSuccess: number[];
	dateFailed: number[];
}
export type RenderDelta = RenderDelta_Serialize;
export type Handler = (...args: unknown[]) => void;
declare const mma: {
	cmd: {
		writeTempFile: (name: string, content: string) => Promise<string>;
		readFile: (path: string) => Promise<string>;
		getDbUri: () => Promise<string>;
		getAppDataDir: () => Promise<string>;
		openDataFolder: () => Promise<null>;
		listUserPlugins: () => Promise<PluginManifest[]>;
		reverseGeocode: (lat: number, lng: number) => Promise<{
			city: string;
			admin: string;
			country: string;
			country_code: string;
		} | null>;
		storeOpenMap: (mapId: string) => Promise<StoreStatus>;
		storeCloseMap: () => Promise<null>;
		storeSaveDirty: () => Promise<SaveResult>;
		storeBakeAndSave: () => Promise<null>;
		storeGetSummary: () => Promise<SummaryResult>;
		storeListMaps: () => Promise<MapMeta[]>;
		storeGetMap: (id: string) => Promise<{
			meta: MapMeta;
		} | null>;
		storeCreateMap: (name: string, folder: string | null) => Promise<MapData>;
		storeDeleteMap: (id: string) => Promise<null>;
		storeUpdateMapMeta: (id: string, patch: MapMetaPatch) => Promise<null>;
		storeTouchMapOpened: (mapId: string) => Promise<null>;
		storeRenameFolder: (from: string, to: string) => Promise<null>;
		storeDeleteFolder: (name: string) => Promise<null>;
		storeMoveMapToFolder: (mapId: string, folder: string | null) => Promise<null>;
		storeUpdateMapLabels: (mapId: string, labels: string[]) => Promise<null>;
		storeGetPanoDate: (panoId: string) => Promise<number | null>;
		storeSetPanoDate: (panoId: string, timestamp: number) => Promise<null>;
		storeDbTableInfo: () => Promise<DbTableInfo[]>;
		storeAddLocations: (locations: Location_Deserialize[]) => Promise<MutationResult_Serialize>;
		storeRemoveLocations: (ids: number[]) => Promise<MutationResult_Serialize>;
		storeUpdateLocations: (updates: [
			number,
			LocationPatch_Deserialize
		][], recordUndo: boolean | null) => Promise<MutationResult_Serialize>;
		storeSetActive: (id: number | null) => Promise<null>;
		storeGetLocation: (id: number) => Promise<{
			id: number;
			lat: number;
			lng: number;
			heading: number;
			pitch: number;
			zoom: number;
			panoId: string | null;
			flags: number;
			tags: number[];
			extra?: any | null;
			createdAt: string;
			modifiedAt?: string | null;
		} | null>;
		storeGetLocationFile: (id: number) => Promise<string | null>;
		storeGetLocationsByIds: (ids: number[]) => Promise<Location_Serialize[]>;
		storeGetAllLocations: () => Promise<string>;
		storeLocationCount: () => Promise<number>;
		storeHasLocation: (id: number) => Promise<boolean>;
		storeBounds: () => Promise<[
			number,
			number,
			number,
			number
		] | null>;
		storeFindNearby: (lat: number, lng: number, radiusM: number) => Promise<Location_Serialize[]>;
		storeExtraFieldValues: (field: string) => Promise<string[]>;
		storeCreateTags: (names: string[]) => Promise<MutationResult_Serialize>;
		storeUpdateTag: (tagId: number, name: string | null, color: string | null) => Promise<MutationResult_Serialize>;
		storeDeleteTags: (tagIds: number[]) => Promise<MutationResult_Serialize>;
		storeStripTags: (tagIds: number[]) => Promise<MutationResult_Serialize>;
		storeReorderTags: (orderedIds: number[]) => Promise<MutationResult_Serialize>;
		storeTagCounts: () => Promise<{
			[x: number]: number;
		}>;
		storeUndo: () => Promise<MutationResult_Serialize>;
		storeRedo: () => Promise<MutationResult_Serialize>;
		storeResetUndo: () => Promise<null>;
		storeCommitDiff: () => Promise<[
			number,
			number,
			number
		]>;
		storeSyncSelections: (sels: SelectionInput[]) => Promise<SyncSelectionsResult>;
		storeAddSelection: (props: SelectionProps) => Promise<SelectionResult>;
		storeRemoveSelection: (key: string) => Promise<number>;
		storeResetSelections: () => Promise<number>;
		storeGetSelections: () => Promise<SelectionSummary[]>;
		storeGetSelectedIds: () => Promise<number[]>;
		storeGetSelectedIdsList: () => Promise<number[]>;
		storeSetSelectedIds: (ids: number[]) => Promise<null>;
		storeResolveSelection: (props: SelectionProps) => Promise<number[]>;
		storeRefreshSelections: () => Promise<number>;
		storeFillRenderFile: (req: RenderRequest) => Promise<string>;
		storeResolvePick: (cell: string, cellIndex: number) => Promise<number | null>;
		bulkImportPreview: (path: string) => Promise<ImportPreviewEntry[]>;
		bulkImportConfirm: (path: string, selectedIndices: number[]) => Promise<ImportedMapInfo[]>;
		storeImportPreview: (path: string) => Promise<EditorImportPreview>;
		storeImportFile: (droppedFields: string[]) => Promise<EditorImportResult_Serialize>;
		storeImportPaste: (text: string) => Promise<[
			EditorImportResult_Serialize,
			number | null
		]>;
		storeExportJson: (opts: ExportOpts) => Promise<string>;
		storeExportCsv: (scope: number[] | null) => Promise<string>;
		storeExportGeojson: (scope: number[] | null, tagsJson: string) => Promise<string>;
		storeExportBulkZip: () => Promise<string>;
		storeSnapshotCommit: () => Promise<CommitBlobEntry[]>;
		storeRestoreCommit: (mapId: string, blobs: CommitBlobEntry[]) => Promise<null>;
		storeDbClearTable: (table: string) => Promise<number>;
		storeDbStats: () => Promise<DbStats>;
		storeSeenWrite: (entry: SeenWriteEntry) => Promise<null>;
		storeSeenList: (limit: number, offset: number, filter: {
			country?: string | null;
			mapId?: string | null;
			search?: string | null;
		} | null) => Promise<SeenEntry[]>;
		storeSeenCount: (filter: {
			country?: string | null;
			mapId?: string | null;
			search?: string | null;
		} | null) => Promise<number>;
		storeSeenCountries: () => Promise<string[]>;
		storeSeenMaps: () => Promise<SeenMapInfo[]>;
		storeSeenClear: () => Promise<null>;
		storeCreateCommit: (mapId: string, message: string | null, diff: {
			added?: number;
			removed?: number;
			modified?: number;
		} | null) => Promise<string>;
		storeListCommits: (mapId: string) => Promise<CommitInfo[]>;
		storeCheckoutCommit: (mapId: string, commitId: string) => Promise<null>;
	};
	invoke: typeof invoke;
	shell: {
		Command: typeof Command;
	};
	dialog: {
		open: typeof open$1;
		save: typeof save;
	};
	registerPlugin: typeof registerPlugin;
	registerEnrichFields: typeof registerEnrichFields;
	registerEnrichmentProvider: typeof registerEnrichmentProvider;
	createLocation: typeof createLocation;
	getGoogleMap: () => google.maps.Map | null;
	setSetting: typeof setSetting;
	getSettings: () => {
		showCameraBadges: boolean;
		showLinksControl: boolean;
		clickToGo: boolean;
		showRoadLabels: boolean;
		defaultMovementMode: MovementMode;
		showCar: boolean;
		showCrosshair: boolean;
		showCompass: boolean;
		showZoom: boolean;
		showReturnToSpawn: boolean;
		showJumpButtons: boolean;
		showMapLinks: boolean;
		showCoordinateDisplay: boolean;
		showFullscreenButton: boolean;
		showPanoMetadata: boolean;
		showExactDate: boolean;
		exactDateFormat: ExactDateFormat;
		dateTimezone: DateTimezone;
		showNavArrow: boolean;
		showGroundArrow: boolean;
		hidePanoUI: boolean;
		fullscreenMap: boolean;
		showFullscreenMinimap: boolean;
		showFullscreenTagbar: boolean;
		customCss: string;
		enableSeen: boolean;
		enableSeenThumbnails: boolean;
		seenResolution: SeenResolution;
		mapPanSpeed: number;
		mapZoomSpeed: number;
		panoLookSpeed: number;
		slowModifier: number;
		showFps: boolean;
		mapListFields: MapListField[];
		geocodeProvider: GeocodeProvider;
		nominatimApiKey: string;
		tagViewMode: TagViewMode;
		savedSelections: SavedSelection[];
	};
	on(event: EditorEvent, handler: Handler): () => void;
	getSeenEntries: typeof getSeenEntries;
	getSeenCount: typeof getSeenCount;
	clearSeen: typeof clearSeen;
	loadSeenPano: typeof loadSeenPano;
	enrichAll: (opts?: Record<string, unknown>) => Promise<EnrichResult>;
	bulkPinToPano: (opts?: Record<string, unknown>) => Promise<number>;
	validateLocations: typeof validateLocations;
	needsEnrichment: (loc: Pick<Location$1, "extra">) => boolean;
	useMapList(): MapMeta[];
	invalidateMapList(): Promise<void>;
	useTagCounts(): Record<number, number>;
	getTagCounts(): Record<number, number>;
	refreshAfterMutation(): void;
	useCurrentMap(): MapData | null;
	getVisibleTags(): Tag$1[];
	useMapVersion(): number;
	useSelectedLocationIds(): Set<number>;
	useActiveLocation(): Location$1 | null;
	useDuplicateLocations(): Location$1[];
	useWorkArea(): WorkArea;
	useReview(): {
		locations: number[];
		index: number;
	} | null;
	hasCommitDiff(): boolean;
	useCommitDiff(): {
		added: number;
		removed: number;
		modified: number;
	};
	getDirtyCount(): Promise<number>;
	scheduleSave(): void;
	flushSave(): Promise<void>;
	initStore(): Promise<void>;
	openMap(id: string, pushHistory?: boolean): Promise<void>;
	closeMap(pushHistory?: boolean): Promise<void>;
	getCurrentMapId(): string | null;
	getCurrentMap(): MapData | null;
	getActiveLocation(): Location$1 | null;
	fetchAllLocations(): Promise<Location$1[]>;
	fetchLocation(id: number): Promise<Location$1 | null>;
	fetchLocationsByIds(ids: number[]): Promise<Location$1[]>;
	getSelections(): Selection$1[];
	getSelectedLocationIds(): Set<number>;
	syncSelections(): Promise<{
		ids: number[];
	}>;
	createMap(name: string, folder?: string | null): Promise<void>;
	deleteMap(id: string): Promise<void>;
	renameFolder(from: string, to: string): Promise<void>;
	moveMapToFolder(mapId: string, folder: string | null): Promise<void>;
	deleteFolder(name: string): Promise<void>;
	getAllMaps(): Promise<MapData[]>;
	renameMap(id: string, name: string): Promise<void>;
	updateMapLabels(id: string, labels: string[]): Promise<void>;
	updateMapMeta(patch: MapMetaPatch): Promise<void>;
	setMapExtraFields(fields: Record<string, ExtraFieldDef>): Promise<void>;
	mutate(p: Promise<MutationResult_Serialize>): Promise<MutationResult_Serialize>;
	addLocations(locs: Location$1[], opts?: {
		hideInDelta?: boolean;
	}): Promise<void>;
	duplicateLocation(locId: number): Promise<number | null>;
	updateLocationNoUndo(id: number, patch: Partial<Location$1>): Promise<MutationResult_Serialize>;
	removeLocations(ids: Set<number>): void;
	updateLocation(locId: number, patch: Partial<Location$1>): void;
	batchUpdateLocations(updates: {
		id: number;
		patch: Partial<Location$1>;
	}[]): Promise<void | MutationResult_Serialize>;
	patchLocationExtra(locId: number, extraPatch: Record<string, unknown>, replace?: boolean): void;
	useSelections(): Selection$1[];
	useSelectionVersion(): number;
	addSelection(props: SelectionProps): Promise<void>;
	removeSelection(key: string): Promise<void>;
	resetSelections(): Promise<void>;
	selectIntersection(keys?: string[] | null): Promise<void>;
	selectUnion(keys?: string[] | null): Promise<void>;
	selectInverse(keys?: string[] | null): Promise<void>;
	toggleManualSelection(locationId: number): Promise<void>;
	selectEverything(): Promise<void>;
	selectUntagged(): Promise<void>;
	selectUnpanned(): Promise<void>;
	selectPanoIds(): Promise<void>;
	selectNotPanoIds(): Promise<void>;
	selectDuplicates(distance: number): Promise<void>;
	selectTag(tagId: number): Promise<void>;
	selectPolygon(polygon: PolygonGeometry, includeInformational?: boolean): Promise<void>;
	selectFilter(field: string, op: FilterOp, value: unknown, value2?: unknown): Promise<void>;
	setPolygonName(key: string, name: string): Promise<void>;
	setSelectionColor(key: string, color: [
		number,
		number,
		number
	]): void;
	reorderSelection(fromKey: string, toKey: string, position: "before" | "after"): void;
	composeSelections(dragKey: string, dropKey: string, mode: "intersection" | "union", dragParent: string | null, dropParent: string | null): void;
	decomposeChild(parentKey: string, childKey: string): void;
	removeChildFromSelection(parentKey: string, childKey: string): void;
	toggleTagSelections(tagIds: number[]): void;
	useSelectedTagIds(): Set<number>;
	setActiveLocation(id: number | null, checkDuplicates?: boolean): Promise<void>;
	openDuplicateLocation(loc: Location$1): void;
	removeDuplicate(id: number): void;
	closeDuplicates(): void;
	setWorkArea(area: WorkArea): void;
	useActivePluginId(): string | null;
	getWorkArea(): WorkArea;
	getActivePluginId(): string | null;
	setPluginMode(pluginId: string): void;
	exitPluginMode(): void;
	createTags(names: string[]): Promise<Tag$1[]>;
	updateTags(patches: {
		id: number;
		patch: Partial<Tag$1>;
	}[]): Promise<void>;
	deleteTags(tagIds: number[]): Promise<void>;
	reorderTags(orderedIds: number[]): Promise<void>;
	addTagToLocations(tagId: number, locationIds: number[]): Promise<void>;
	removeTagFromLocations(tagId: number, locationIds: number[]): Promise<void>;
	removeTagFromAllLocations(tagId: number): Promise<void>;
	importFile(droppedFields: string[]): Promise<EditorImportResult_Serialize>;
	importPaste(text: string): Promise<readonly [
		EditorImportResult_Serialize,
		number | null
	]>;
	beginReview(locationIds: number[]): Promise<void>;
	cancelReview(): void;
	reviewNext(): Promise<void>;
	reviewPrev(): Promise<void>;
	reviewDelete(): Promise<void>;
	undo(): Promise<void>;
	redo(): Promise<void>;
	getUndoRedoState(): {
		canUndo: boolean;
		canRedo: boolean;
	};
	useUndoRedo(): {
		canUndo: boolean;
		canRedo: boolean;
	};
	commitMap(message?: string): Promise<string>;
	checkoutCommit(commitId: string): Promise<void>;
	renderDeltaBus: {
		on: (fn: (delta: RenderDelta) => void) => () => void;
		emit: (delta: RenderDelta) => void;
	};
	selBitmaskBus: {
		on: (fn: (selColors: [
			number,
			number,
			number
		][], cellEntries: {
			cellChar: string;
			locCount: number;
			masks: Uint8Array[];
		}[], setIds: (ids: Set<number>) => void) => void) => () => void;
		emit: (selColors: [
			number,
			number,
			number
		][], cellEntries: {
			cellChar: string;
			locCount: number;
			masks: Uint8Array[];
		}[], setIds: (ids: Set<number>) => void) => void;
	};
	ready: boolean;
};
type MMA$1 = typeof mma;

export {
	MMA$1 as MMAApi,
	Plugin$1 as MMAPlugin,
};

export {};

declare global {
	const MMA: typeof mmaApi;
}
